Repository KEEPER31337/Homepage-Back, pull requests merged in 2022-06, with the labels that each got.

#303 Feature/#280 공모전 대외활동 정보 자동화
  build.gradle
  src/main/java/keeper/project/homepage/KeeperApplication.java
  src/main/java/keeper/project/homepage/admin/crawler/CrawlerSettings.java
  src/main/java/keeper/project/homepage/admin/crawler/KeeperCrawler.java
  src/main/java/keeper/project/homepage/admin/crawler/Linkareer.java
  src/main/java/keeper/project/homepage/admin/crawler/ScheduledTasks.java
  src/main/java/keeper/project/homepage/repository/member/MemberHasMemberJobRepository.java
  src/main/java/keeper/project/homepage/user/service/posting/PostingService.java
Labels: feat, refactor

#307 fix: CTF 문서 오류 수정
  src/main/java/keeper/project/homepage/admin/dto/ctf/CtfChallengeAdminDto.java
  src/main/java/keeper/project/homepage/user/dto/ctf/CtfChallengeDto.java
  src/test/java/keeper/project/homepage/admin/controller/ctf/CtfAdminControllerTest.java
Labels: fix

#313 Feature/ctf 추가 수정 사항 #312
  src/docs/asciidoc/ctf/ctfExtraData.adoc
  src/main/java/keeper/project/homepage/admin/controller/ctf/CtfAdminController.java
  src/main/java/keeper/project/homepage/admin/dto/ctf/CtfContestAdminDto.java
  src/main/java/keeper/project/homepage/admin/service/ctf/CtfAdminService.java
  src/main/java/keeper/project/homepage/entity/ctf/CtfContestEntity.java
  src/main/java/keeper/project/homepage/repository/ctf/CtfContestRepository.java
  src/main/java/keeper/project/homepage/repository/ctf/CtfTeamRepository.java
  src/main/java/keeper/project/homepage/user/controller/ctf/CtfChallengeController.java
  src/main/java/keeper/project/homepage/user/controller/ctf/CtfExtraDataController.java
  src/main/java/keeper/project/homepage/user/controller/ctf/CtfTeamController.java
  src/main/java/keeper/project/homepage/user/dto/ctf/CtfContestDto.java
  src/main/java/keeper/project/homepage/user/dto/ctf/CtfJoinTeamRequestDto.java
  src/main/java/keeper/project/homepage/user/service/ctf/CtfExtraDataService.java
  src/main/java/keeper/project/homepage/user/service/ctf/CtfTeamService.java
  src/test/java/keeper/project/homepage/admin/controller/ctf/CtfAdminControllerTest.java
  src/test/java/keeper/project/homepage/user/controller/ctf/CtfExtraDataControllerTest.java
  src/test/java/keeper/project/homepage/user/controller/ctf/CtfTeamControllerTest.java
Labels: feat, fix

#315 Feature/ctf 추가 요청 사항 #314
  src/main/java/keeper/project/homepage/admin/dto/ctf/CtfContestAdminDto.java
  src/main/java/keeper/project/homepage/user/dto/ctf/CtfContestDto.java
  src/main/java/keeper/project/homepage/user/dto/ctf/CtfTeamDetailDto.java
  src/main/java/keeper/project/homepage/user/service/ctf/CtfChallengeService.java
  src/main/java/keeper/project/homepage/user/service/ctf/CtfTeamService.java
  src/main/java/keeper/project/homepage/util/service/CtfUtilService.java
  src/test/java/keeper/project/homepage/controller/ctf/CtfSpringTestHelper.java
  src/test/java/keeper/project/homepage/user/controller/ctf/CtfChallengeControllerTest.java
  src/test/java/keeper/project/homepage/user/controller/ctf/CtfExtraDataControllerTest.java
  src/test/java/keeper/project/homepage/user/controller/ctf/CtfTeamControllerTest.java
Labels: feat

#317 Feature/ctf 팀 관련 수정사항 #316
  src/docs/asciidoc/ctf/ctfTeam.adoc
  src/main/java/keeper/project/homepage/repository/ctf/CtfFlagRepository.java
  src/main/java/keeper/project/homepage/user/service/ctf/CtfTeamService.java
  src/test/java/keeper/project/homepage/user/controller/ctf/CtfTeamControllerTest.java
  src/test/java/keeper/project/homepage/user/service/ctf/CtfTeamServiceTest.java
Labels: fix, docs

#301 Feature/#302 파일, 썸네일, 이미지 리팩토링
  src/docs/asciidoc/badge.adoc
  src/docs/asciidoc/utilAdmin.adoc
  src/main/java/keeper/project/homepage/admin/controller/library/BookManageController.java
  src/main/java/keeper/project/homepage/admin/controller/posting/AdminPostingController.java
  src/main/java/keeper/project/homepage/admin/controller/util/AdminBadgeController.java
  src/main/java/keeper/project/homepage/admin/service/about/AdminStaticWriteSubtitleImageService.java
  src/main/java/keeper/project/homepage/admin/service/ctf/CtfAdminService.java
  src/main/java/keeper/project/homepage/common/controller/util/ImageController.java
  src/main/java/keeper/project/homepage/entity/member/MemberEntity.java
  src/main/java/keeper/project/homepage/exception/ExceptionAdvice.java
  src/main/java/keeper/project/homepage/exception/file/CustomInvalidImageFileException.java
  src/main/java/keeper/project/homepage/user/controller/posting/PostingController.java
  src/main/java/keeper/project/homepage/user/dto/library/BookResult.java
  src/main/java/keeper/project/homepage/user/dto/posting/PostingBestDto.java
  src/main/java/keeper/project/homepage/user/dto/posting/PostingResponseDto.java
  src/main/java/keeper/project/homepage/user/service/member/MemberDeleteService.java
  src/main/java/keeper/project/homepage/user/service/member/MemberService.java
  src/main/java/keeper/project/homepage/user/service/study/StudyService.java
  src/main/java/keeper/project/homepage/util/ImageProcessing.java
  src/main/java/keeper/project/homepage/util/image/ImageFormatChecking.java
  src/main/java/keeper/project/homepage/util/image/preprocessing/ImageCenterCropping.java
  src/main/java/keeper/project/homepage/util/image/preprocessing/ImageNoChange.java
  src/main/java/keeper/project/homepage/util/image/preprocessing/ImagePreprocessing.java
  src/main/java/keeper/project/homepage/util/image/preprocessing/ImageResizing.java
  src/main/java/keeper/project/homepage/util/image/preprocessing/ImageSize.java
  src/main/java/keeper/project/homepage/util/service/FileService.java
  src/main/java/keeper/project/homepage/util/service/ThumbnailService.java
  src/main/resources/exception.properties
  src/test/java/keeper/project/homepage/ApiControllerTestHelper.java
  src/test/java/keeper/project/homepage/admin/controller/util/AdminBadgeControllerTest.java
  src/test/java/keeper/project/homepage/controller/posting/CommentControllerTest.java
  src/test/java/keeper/project/homepage/service/ThumbnailServiceTest.java
Labels: feat, refactor

#305 Feature/#265 member refactor
  src/docs/asciidoc/member_info.adoc
  src/main/java/keeper/project/homepage/admin/controller/member/AdminMemberController.java
  src/main/java/keeper/project/homepage/admin/service/member/AdminMemberService.java
  src/main/java/keeper/project/homepage/admin/service/member/AdminMemberUtilService.java
  src/main/java/keeper/project/homepage/admin/service/posting/AdminCommentService.java
  src/main/java/keeper/project/homepage/repository/member/MemberRepository.java
  src/main/java/keeper/project/homepage/user/controller/member/MemberController.java
  src/main/java/keeper/project/homepage/user/service/member/MemberDeleteService.java
  src/main/java/keeper/project/homepage/user/service/member/MemberService.java
  src/main/java/keeper/project/homepage/user/service/member/MemberUtilService.java
  src/main/java/keeper/project/homepage/user/service/posting/CommentService.java
  src/main/java/keeper/project/homepage/user/service/posting/PostingService.java
  src/test/java/keeper/project/homepage/controller/member/MemberControllerTest.java
  src/test/java/keeper/project/homepage/service/member/MemberServiceTest.java
  src/test/java/keeper/project/homepage/user/controller/member/MemberControllerTest.java
Labels: refactor, docs, test

#323 Feature/ctf 추가 요청 사항 #321
  src/docs/asciidoc/ctf/ctfAdmin.adoc
  src/main/java/keeper/project/homepage/admin/controller/ctf/CtfAdminController.java
  src/main/java/keeper/project/homepage/admin/dto/ctf/CtfSubmitLogDto.java
  src/main/java/keeper/project/homepage/admin/service/ctf/CtfAdminService.java
  src/main/java/keeper/project/homepage/entity/ctf/CtfSubmitLogEntity.java
  src/main/java/keeper/project/homepage/repository/ctf/CtfContestRepository.java
  src/main/java/keeper/project/homepage/repository/ctf/CtfSubmitLogRepository.java
  src/main/java/keeper/project/homepage/user/service/ctf/CtfChallengeService.java
  src/test/java/keeper/project/homepage/admin/controller/ctf/CtfAdminControllerTest.java
  src/test/java/keeper/project/homepage/controller/ctf/CtfSpringTestHelper.java
  src/test/java/keeper/project/homepage/repository/ctf/CtfSubmitLogRepositoryTest.java
Labels: feat, fix
