Repository KEEPER31337/Homepage-Back, pull requests merged in 2022-09, with the labels that each got.

#384 Feature/활동조사 추가요청 api #381
  src/docs/asciidoc/clerk/survey.adoc
  src/docs/asciidoc/clerk/surveyAdmin.adoc
  src/main/java/keeper/project/homepage/admin/controller/clerk/AdminSurveyController.java
  src/main/java/keeper/project/homepage/admin/dto/clerk/request/AdminSurveyRequestDto.java
  src/main/java/keeper/project/homepage/admin/dto/clerk/response/SurveyResponseDto.java
  src/main/java/keeper/project/homepage/admin/service/clerk/AdminSurveyService.java
  src/main/java/keeper/project/homepage/entity/clerk/SurveyMemberReplyEntity.java
  src/main/java/keeper/project/homepage/entity/clerk/SurveyReplyExcuseEntity.java
  src/main/java/keeper/project/homepage/repository/clerk/SurveyMemberReplyRepository.java
  src/main/java/keeper/project/homepage/repository/clerk/SurveyRepository.java
  src/main/java/keeper/project/homepage/user/controller/clerk/SurveyController.java
  src/main/java/keeper/project/homepage/user/dto/clerk/request/SurveyResponseRequestDto.java
  src/main/java/keeper/project/homepage/user/dto/clerk/response/ClosedSurveyInformationResponseDto.java
  src/main/java/keeper/project/homepage/user/dto/clerk/response/SurveyInformationResponseDto.java
  src/main/java/keeper/project/homepage/user/service/clerk/SurveyService.java
  src/main/java/keeper/project/homepage/util/service/SurveyUtilService.java
  src/test/java/keeper/project/homepage/admin/controller/clerk/AdminSurveyControllerTest.java
  src/test/java/keeper/project/homepage/admin/service/clerk/AdminSurveyServiceTest.java
  src/test/java/keeper/project/homepage/controller/clerk/SurveySpringTestHelper.java
  src/test/java/keeper/project/homepage/repository/clerk/SurveyRepositoryTest.java
  src/test/java/keeper/project/homepage/repository/clerk/SurveyRepositoryTestHelper.java
  src/test/java/keeper/project/homepage/user/controller/clerk/SurveyControllerTest.java
  src/test/java/keeper/project/homepage/user/service/clerk/SurveyServiceTest.java
Labels: feat, fix, docs, test

#396 fix: 활동조사 추가 수정사항
  src/main/java/keeper/project/homepage/user/dto/clerk/response/ClosedSurveyInformationResponseDto.java
  src/main/java/keeper/project/homepage/user/service/clerk/SurveyService.java
  src/test/java/keeper/project/homepage/user/service/clerk/SurveyServiceTest.java
Labels: fix

#395 fix: 직책 삭제 안되던 버그 해결
  src/main/java/keeper/project/homepage/admin/service/systemadmin/SystemAdminService.java
  src/main/java/keeper/project/homepage/entity/member/MemberEntity.java
  src/test/java/keeper/project/homepage/ApiControllerTestHelper.java
  src/test/java/keeper/project/homepage/admin/controller/systemadmin/SystemAdminControllerTest.java
  src/test/java/keeper/project/homepage/admin/service/clerk/AdminClerkServiceTest.java
  src/test/java/keeper/project/homepage/admin/service/systemadmin/SystemAdminServiceTest.java
  src/test/java/keeper/project/homepage/controller/attendance/AttendanceControllerTest.java
  src/test/java/keeper/project/homepage/controller/attendance/GameControllerTest.java
  src/test/java/keeper/project/homepage/controller/attendance/RankControllerTest.java
  src/test/java/keeper/project/homepage/controller/library/BookManageControllerTest.java
  src/test/java/keeper/project/homepage/controller/library/LibraryMainControllerTest.java
  src/test/java/keeper/project/homepage/controller/sign/SignInControllerTest.java
  src/test/java/keeper/project/homepage/controller/sign/SignUpControllerTest.java
  src/test/java/keeper/project/homepage/repository/member/MemberHasCommentDislikeRepositoryTest.java
  src/test/java/keeper/project/homepage/repository/member/MemberHasCommentLikeRepositoryTest.java
  src/test/java/keeper/project/homepage/repository/posting/CommentRepositoryTest.java
  src/test/java/keeper/project/homepage/service/member/MemberHasCommentDislikeServiceTest.java
  src/test/java/keeper/project/homepage/service/posting/CommentServiceTest.java
Labels: fix

#397 Feature/#390 상벌점페이지 추가 요청사항 개발
  src/docs/asciidoc/member_infoAdmin.adoc
  src/main/java/keeper/project/homepage/admin/controller/member/AdminMemberController.java
  src/main/java/keeper/project/homepage/admin/dto/clerk/response/MemberTotalMeritLogsResponseDto.java
  src/main/java/keeper/project/homepage/admin/service/member/AdminMemberService.java
  src/test/java/keeper/project/homepage/ApiControllerTestHelper.java
  src/test/java/keeper/project/homepage/admin/controller/clerk/AdminMeritControllerTest.java
  src/test/java/keeper/project/homepage/admin/controller/member/AdminMemberControllerTest.java
Labels: fix, docs

#398 fix: 없는 file import로 인한 오류 수정
  src/main/java/keeper/project/homepage/admin/controller/member/AdminMemberController.java
  src/main/java/keeper/project/homepage/admin/service/member/AdminMemberService.java
Labels: fix

#399 Feature/#383 출석체크관리페이지 추가요청사항 개발
  src/docs/asciidoc/clerk/clerkSeminar.adoc
  src/main/java/keeper/project/homepage/admin/controller/clerk/AdminSeminarController.java
  src/main/java/keeper/project/homepage/admin/controller/member/AdminMemberController.java
  src/main/java/keeper/project/homepage/admin/dto/clerk/SeminarAttendanceDto.java
  src/main/java/keeper/project/homepage/admin/dto/clerk/request/SeminarWithAttendancesRequestByPeriodDto.java
  src/main/java/keeper/project/homepage/admin/dto/clerk/response/SeminarAttendanceResponseDto.java
  src/main/java/keeper/project/homepage/admin/dto/clerk/response/SeminarWithAttendancesResponseByPeriodDto.java
  src/main/java/keeper/project/homepage/admin/service/clerk/AdminSeminarService.java
  src/main/java/keeper/project/homepage/entity/clerk/SeminarAttendanceExcuseEntity.java
  src/main/java/keeper/project/homepage/repository/clerk/SeminarRepository.java
  src/test/java/keeper/project/homepage/admin/controller/clerk/AdminSeminarControllerTest.java
  src/test/java/keeper/project/homepage/admin/controller/clerk/ClerkControllerTestHelper.java
Labels: fix

#402 출석체크관리페이지 버그수정 및 추가요청 사항 구현
  src/main/java/keeper/project/homepage/admin/dto/clerk/response/SeminarAttendanceResponseDto.java
  src/main/java/keeper/project/homepage/admin/service/clerk/AdminSeminarService.java
  src/main/java/keeper/project/homepage/entity/clerk/SeminarAttendanceEntity.java
  src/test/java/keeper/project/homepage/admin/controller/clerk/AdminSeminarControllerTest.java
  src/test/java/keeper/project/homepage/admin/controller/clerk/ClerkControllerTestHelper.java
Labels: fix

#388 Feature/세미나 자동출석 api 개발 #359
  src/docs/asciidoc/clerk/clerkSeminar.adoc
  src/docs/asciidoc/clerk/seminar.adoc
  src/docs/asciidoc/keeper.adoc
  src/main/java/keeper/project/homepage/admin/controller/clerk/AdminMeritController.java
  src/main/java/keeper/project/homepage/admin/controller/clerk/AdminSeminarController.java
  src/main/java/keeper/project/homepage/admin/dto/clerk/request/AttendanceStartRequestDto.java
  src/main/java/keeper/project/homepage/admin/dto/clerk/response/AttendanceStartResponseDto.java
  src/main/java/keeper/project/homepage/admin/dto/clerk/response/SeminarSearchByDateResponseDto.java
  src/main/java/keeper/project/homepage/admin/service/clerk/AdminSeminarService.java
  src/main/java/keeper/project/homepage/entity/clerk/SeminarEntity.java
  src/main/java/keeper/project/homepage/exception/ExceptionAdvice.java
  src/main/java/keeper/project/homepage/exception/clerk/CustomSeminarAttendanceFailException.java
  src/main/java/keeper/project/homepage/repository/clerk/SeminarAttendanceRepository.java
  src/main/java/keeper/project/homepage/repository/clerk/SeminarRepository.java
  src/main/java/keeper/project/homepage/user/controller/clerk/SeminarController.java
  src/main/java/keeper/project/homepage/user/dto/clerk/request/AttendanceCheckRequestDto.java
  src/main/java/keeper/project/homepage/user/dto/clerk/response/AttendanceCheckResponseDto.java
  src/main/java/keeper/project/homepage/user/dto/clerk/response/SeminarOngoingAttendanceResponseDto.java
  src/main/java/keeper/project/homepage/user/service/clerk/SeminarService.java
  src/main/java/keeper/project/homepage/util/service/SchedulerService.java
  src/main/resources/exception.properties
  src/test/java/keeper/project/homepage/ApiControllerTestHelper.java
  src/test/java/keeper/project/homepage/admin/controller/clerk/AdminSeminarControllerTest.java
  src/test/java/keeper/project/homepage/user/controller/clerk/ClerkControllerTestHelper.java
  src/test/java/keeper/project/homepage/user/controller/clerk/SeminarControllerTest.java
  src/test/java/keeper/project/homepage/util/service/SchedulerServiceTest.java
  src/test/java/keeper/project/homepage/util/service/WebSocketServiceTest.java
Labels: feat, docs, test

#406 Feature/#405 세미나 조회 수정사항
  src/main/java/keeper/project/homepage/admin/controller/clerk/AdminSeminarController.java
  src/main/java/keeper/project/homepage/admin/service/clerk/AdminSeminarService.java
  src/main/java/keeper/project/homepage/user/controller/clerk/SeminarController.java
  src/main/java/keeper/project/homepage/user/service/clerk/SeminarService.java
  src/test/java/keeper/project/homepage/admin/controller/clerk/AdminSeminarControllerTest.java
  src/test/java/keeper/project/homepage/admin/controller/clerk/ClerkControllerTestHelper.java
  src/test/java/keeper/project/homepage/user/controller/clerk/ClerkControllerTestHelper.java
  src/test/java/keeper/project/homepage/user/controller/clerk/SeminarControllerTest.java
Labels: fix

#401 Feature/게시글 내 이미지 삽입
  src/docs/asciidoc/posting.adoc
  src/main/java/keeper/project/homepage/user/controller/posting/PostingController.java
  src/main/java/keeper/project/homepage/user/dto/posting/PostingImageUploadResponseDto.java
  src/main/java/keeper/project/homepage/user/service/posting/PostingService.java
  src/main/java/keeper/project/homepage/util/service/ThumbnailService.java
  src/test/java/keeper/project/homepage/controller/posting/PostingControllerTest.java
Labels: feat

#408 Feature/#407 자동결석체크 수정
  src/main/java/keeper/project/homepage/admin/service/clerk/AdminSeminarService.java
  src/main/java/keeper/project/homepage/config/scheduler/SchedulerConfig.java
  src/main/java/keeper/project/homepage/util/service/SchedulerService.java
Labels: fix

#415 Update issue templates
  .github/ISSUE_TEMPLATE/general-issue-template.md
  PULL_REQUEST_TEMPLATE.md
Labels: 📄 docs

#433 Feature/활동조사 페이지 활동상태 갱신 #432
  src/main/java/keeper/project/homepage/clerk/service/SurveyService.java
  src/test/java/keeper/project/homepage/clerk/service/SurveyServiceTest.java
Labels: 🛠 bug, ✏️ test
