Repository KEEPER31337/Homepage-Back, pull requests merged in 2022-08, with the labels that each got.

#337 Feature/회장선거용 투표 api 개발 #335
  build.gradle
  src/docs/asciidoc/admin.adoc
  src/docs/asciidoc/election/election.adoc
  src/docs/asciidoc/election/electionAdmin.adoc
  src/docs/asciidoc/keeper.adoc
  src/main/java/keeper/project/homepage/admin/controller/election/AdminElectionController.java
  src/main/java/keeper/project/homepage/admin/dto/election/ElectionCandidateDto.java
  src/main/java/keeper/project/homepage/admin/dto/election/request/ElectionCandidateCreateRequestDto.java
  src/main/java/keeper/project/homepage/admin/dto/election/request/ElectionCreateRequestDto.java
  src/main/java/keeper/project/homepage/admin/dto/election/response/ElectionCandidateDeleteResponseDto.java
  src/main/java/keeper/project/homepage/admin/dto/election/response/ElectionDeleteResponseDto.java
  src/main/java/keeper/project/homepage/admin/dto/election/response/ElectionUpdateResponseDto.java
  src/main/java/keeper/project/homepage/admin/dto/election/response/ElectionVoterCreateResponseDto.java
  src/main/java/keeper/project/homepage/admin/service/election/AdminElectionService.java
  src/main/java/keeper/project/homepage/admin/service/member/AdminMemberUtilService.java
  src/main/java/keeper/project/homepage/entity/election/ElectionCandidateEntity.java
  src/main/java/keeper/project/homepage/entity/election/ElectionChartLogEntity.java
  src/main/java/keeper/project/homepage/entity/election/ElectionEntity.java
  src/main/java/keeper/project/homepage/entity/election/ElectionVoterEntity.java
  src/main/java/keeper/project/homepage/entity/election/ElectionVoterPK.java
  src/main/java/keeper/project/homepage/exception/ExceptionAdvice.java
  src/main/java/keeper/project/homepage/exception/election/CustomCloseElectionVoteException.java
  src/main/java/keeper/project/homepage/exception/election/CustomElectionAlreadyVotedException.java
  src/main/java/keeper/project/homepage/exception/election/CustomElectionCandidateExistException.java
  src/main/java/keeper/project/homepage/exception/election/CustomElectionCandidateNotFoundException.java
  src/main/java/keeper/project/homepage/exception/election/CustomElectionIsNotClosedException.java
  src/main/java/keeper/project/homepage/exception/election/CustomElectionNotFoundException.java
  src/main/java/keeper/project/homepage/exception/election/CustomElectionNotMatchCandidateException.java
  src/main/java/keeper/project/homepage/exception/election/CustomElectionVoteCountNotMatchException.java
  src/main/java/keeper/project/homepage/exception/election/CustomElectionVoteDuplicationJobException.java
  src/main/java/keeper/project/homepage/exception/election/CustomElectionVoterExistException.java
  src/main/java/keeper/project/homepage/exception/election/CustomElectionVoterNotFoundException.java
  src/main/java/keeper/project/homepage/repository/election/ElectionCandidateRepository.java
  src/main/java/keeper/project/homepage/repository/election/ElectionChartLogRepository.java
  src/main/java/keeper/project/homepage/repository/election/ElectionRepository.java
  src/main/java/keeper/project/homepage/repository/election/ElectionVoterRepository.java
  src/main/java/keeper/project/homepage/user/controller/election/ElectionController.java
  src/main/java/keeper/project/homepage/user/dto/election/request/ElectionVoteRequestDto.java
  src/main/java/keeper/project/homepage/user/dto/election/response/ElectionCandidatesResponseDto.java
  src/main/java/keeper/project/homepage/user/dto/election/response/ElectionResponseDto.java
  src/main/java/keeper/project/homepage/user/dto/election/response/ElectionResultResponseDto.java
  src/main/java/keeper/project/homepage/user/service/election/ElectionService.java
  src/main/java/keeper/project/homepage/user/service/member/MemberUtilService.java
  src/main/java/keeper/project/homepage/util/service/ElectionUtilService.java
  src/main/resources/exception.properties
  src/test/java/keeper/project/homepage/admin/controller/election/AdminElectionControllerTest.java
  src/test/java/keeper/project/homepage/admin/service/election/AdminElectionServiceTest.java
  src/test/java/keeper/project/homepage/controller/election/ElectionSpringTestHelper.java
  src/test/java/keeper/project/homepage/user/controller/election/ElectionControllerTest.java
  src/test/java/keeper/project/homepage/user/service/election/ElectionServiceTest.java
Labels: feat

#339 Feature/#338 선거 api 수정
  src/docs/asciidoc/keeper.adoc
  src/main/java/keeper/project/homepage/exception/ExceptionAdvice.java
  src/test/java/keeper/project/homepage/admin/controller/election/AdminElectionControllerTest.java
  src/test/java/keeper/project/homepage/user/controller/election/ElectionControllerTest.java
Labels: fix

#342 Feature/#341 선거 api 수정 요청
  src/main/java/keeper/project/homepage/user/dto/election/response/ElectionCandidatesResponseDto.java
  src/main/java/keeper/project/homepage/user/service/election/ElectionService.java
  src/test/java/keeper/project/homepage/user/controller/election/ElectionControllerTest.java
Labels: fix

#340 Feature/#336 실시간 투표 현황
  build.gradle
  src/main/java/keeper/project/homepage/admin/controller/election/AdminElectionController.java
  src/main/java/keeper/project/homepage/admin/service/election/AdminElectionService.java
  src/main/java/keeper/project/homepage/config/socket/WebSocketConfig.java
  src/main/java/keeper/project/homepage/repository/election/ElectionVoterRepository.java
  src/main/java/keeper/project/homepage/user/controller/election/ElectionController.java
  src/main/java/keeper/project/homepage/user/dto/election/response/ElectionVoteStatus.java
  src/main/java/keeper/project/homepage/user/service/election/ElectionService.java
  src/main/java/keeper/project/homepage/util/service/WebSocketService.java
  src/test/java/keeper/project/homepage/repository/election/ElectionRepositoryTest.java
  src/test/java/keeper/project/homepage/repository/election/ElectionRepositoryTestHelper.java
  src/test/java/keeper/project/homepage/repository/election/ElectionVoterRepositoryTest.java
  src/test/java/keeper/project/homepage/util/service/WebSocketServiceTest.java
Labels: feat

#345 fix: websocket test build
  src/test/java/keeper/project/homepage/util/service/WebSocketServiceTest.java
Labels: fix

#346 Feature/#343 선거 api 추가 요청 사항
  src/docs/asciidoc/election/election.adoc
  src/docs/asciidoc/election/electionAdmin.adoc
  src/main/java/keeper/project/homepage/admin/controller/election/AdminElectionController.java
  src/main/java/keeper/project/homepage/admin/dto/election/response/ElectionVoterResponseDto.java
  src/main/java/keeper/project/homepage/admin/service/election/AdminElectionService.java
  src/main/java/keeper/project/homepage/repository/election/ElectionCandidateRepository.java
  src/main/java/keeper/project/homepage/repository/election/ElectionRepository.java
  src/main/java/keeper/project/homepage/repository/election/ElectionVoterRepository.java
  src/main/java/keeper/project/homepage/user/controller/election/ElectionController.java
  src/main/java/keeper/project/homepage/user/dto/election/response/ElectionCandidatesResponseDto.java
  src/main/java/keeper/project/homepage/user/service/election/ElectionService.java
  src/main/java/keeper/project/homepage/util/service/ElectionUtilService.java
  src/test/java/keeper/project/homepage/admin/controller/election/AdminElectionControllerTest.java
  src/test/java/keeper/project/homepage/user/controller/election/ElectionControllerTest.java
Labels: feat

#348 fix: docs에 존재하는 오타 수정
  src/docs/asciidoc/ctf/ctfAdmin.adoc
  src/docs/asciidoc/posting/comment.adoc
Labels: fix

#350 fix: 선거 종료 시 현황 확인 가능하도록 변경
  src/main/java/keeper/project/homepage/admin/controller/election/AdminElectionController.java
  src/main/java/keeper/project/homepage/admin/service/election/AdminElectionService.java
Labels: fix

#368 feat: 세미나 Entity, Repository, Repository Test 구현
  src/main/java/keeper/project/homepage/entity/clerk/SeminarAttendanceEntity.java
  src/main/java/keeper/project/homepage/entity/clerk/SeminarAttendanceExcuseEntity.java
  src/main/java/keeper/project/homepage/entity/clerk/SeminarAttendanceStatusEntity.java
  src/main/java/keeper/project/homepage/entity/clerk/SeminarEntity.java
  src/main/java/keeper/project/homepage/repository/clerk/SeminarAttendanceExcuseRepository.java
  src/main/java/keeper/project/homepage/repository/clerk/SeminarAttendanceRepository.java
  src/main/java/keeper/project/homepage/repository/clerk/SeminarAttendanceStatusRepository.java
  src/main/java/keeper/project/homepage/repository/clerk/SeminarRepository.java
  src/test/java/keeper/project/homepage/repository/clerk/SeminarAttendanceRepositoryTest.java
  src/test/java/keeper/project/homepage/repository/clerk/SeminarAttendanceStatusRepositoryTest.java
  src/test/java/keeper/project/homepage/repository/clerk/SeminarRepositoryTestHelper.java
Labels: feat

#369 Feature/활동인원 조사관련 entity repository개발#351
  src/main/java/keeper/project/homepage/entity/clerk/SurveyEntity.java
  src/main/java/keeper/project/homepage/entity/clerk/SurveyMemberReplyEntity.java
  src/main/java/keeper/project/homepage/entity/clerk/SurveyReplyEntity.java
  src/main/java/keeper/project/homepage/entity/clerk/SurveyReplyExcuseEntity.java
  src/main/java/keeper/project/homepage/repository/clerk/SurveyMemberReplyRepository.java
  src/main/java/keeper/project/homepage/repository/clerk/SurveyReplyExcuseRepository.java
  src/main/java/keeper/project/homepage/repository/clerk/SurveyReplyRepository.java
  src/main/java/keeper/project/homepage/repository/clerk/SurveyRepository.java
  src/test/java/keeper/project/homepage/repository/clerk/SurveyReplyRepositoryTest.java
  src/test/java/keeper/project/homepage/repository/clerk/SurveyRepositoryTest.java
  src/test/java/keeper/project/homepage/repository/clerk/SurveyTestHelper.java
Labels: feat

#370 Feature/직책 임명 api 개발 #360
  src/docs/asciidoc/admin.adoc
  src/docs/asciidoc/clerk/clerkAdmin.adoc
  src/main/java/keeper/project/homepage/admin/controller/clerk/AdminClerkController.java
  src/main/java/keeper/project/homepage/admin/dto/clerk/request/AssignJobRequestDto.java
  src/main/java/keeper/project/homepage/admin/dto/clerk/request/DeleteJobRequestDto.java
  src/main/java/keeper/project/homepage/admin/dto/clerk/response/ClerkMemberJobTypeResponseDto.java
  src/main/java/keeper/project/homepage/admin/dto/clerk/response/JobResponseDto.java
  src/main/java/keeper/project/homepage/admin/dto/clerk/response/TypeResponseDto.java
  src/main/java/keeper/project/homepage/admin/service/clerk/AdminClerkService.java
  src/main/java/keeper/project/homepage/entity/member/MemberJobEntity.java
  src/main/java/keeper/project/homepage/entity/member/MemberTypeEntity.java
  src/main/java/keeper/project/homepage/exception/ExceptionAdvice.java
  src/main/java/keeper/project/homepage/exception/clerk/CustomClerkInaccessibleJobException.java
  src/main/java/keeper/project/homepage/repository/member/MemberHasMemberJobRepository.java
  src/main/java/keeper/project/homepage/repository/member/MemberRepository.java
  src/main/java/keeper/project/homepage/user/service/member/MemberUtilService.java
  src/main/resources/exception.properties
  src/test/java/keeper/project/homepage/ApiControllerTestHelper.java
  src/test/java/keeper/project/homepage/admin/controller/clerk/AdminClerkControllerTest.java
  src/test/java/keeper/project/homepage/admin/controller/clerk/ClerkControllerTestHelper.java
  src/test/java/keeper/project/homepage/admin/service/clerk/AdminClerkServiceTest.java
Labels: feat, docs, test

#372 test: 테스트 시 뱃지 이미지 경로 request context 문제 해결
  src/test/java/keeper/project/homepage/admin/service/clerk/AdminClerkServiceTest.java
Labels: fix, test

#380 fix: 404 에러 해결 (GetMapping 누락)
  src/main/java/keeper/project/homepage/user/controller/clerk/SurveyController.java
  src/main/java/keeper/project/homepage/user/service/clerk/SurveyService.java
Labels: fix
