Repository KEEPER31337/Homepage-Back, pull requests merged in 2022-10, with the labels that each got.

#436 CTF 코드 리팩토링
  src/main/java/keeper/project/homepage/ctf/controller/CtfAdminController.java
  src/main/java/keeper/project/homepage/ctf/controller/CtfChallengeController.java
  src/main/java/keeper/project/homepage/ctf/controller/CtfExtraDataController.java
  src/main/java/keeper/project/homepage/ctf/controller/CtfRankingController.java
  src/main/java/keeper/project/homepage/ctf/controller/CtfTeamController.java
  src/main/java/keeper/project/homepage/ctf/entity/CtfChallengeCategoryEntity.java
  src/main/java/keeper/project/homepage/ctf/entity/CtfChallengeTypeEntity.java
  src/main/java/keeper/project/homepage/ctf/service/CtfAdminService.java
  src/main/java/keeper/project/homepage/ctf/service/CtfChallengeService.java
  src/main/java/keeper/project/homepage/ctf/service/CtfExtraDataService.java
  src/main/java/keeper/project/homepage/ctf/service/CtfRankingService.java
  src/main/java/keeper/project/homepage/ctf/service/CtfTeamService.java
  src/main/java/keeper/project/homepage/util/service/CtfUtilService.java
  src/test/java/keeper/project/homepage/ctf/controller/CtfAdminControllerTest.java
  src/test/java/keeper/project/homepage/ctf/controller/CtfChallengeControllerTest.java
  src/test/java/keeper/project/homepage/ctf/controller/CtfSpringTestHelper.java
  src/test/java/keeper/project/homepage/ctf/controller/CtfTeamControllerTest.java
  src/test/java/keeper/project/homepage/ctf/repository/CtfChallengeCategoryRepositoryTest.java
  src/test/java/keeper/project/homepage/ctf/repository/CtfChallengeRepositoryTest.java
  src/test/java/keeper/project/homepage/ctf/repository/CtfChallengeTypeRepositoryTest.java
  src/test/java/keeper/project/homepage/ctf/repository/CtfFlagRepositoryTest.java
  src/test/java/keeper/project/homepage/ctf/repository/CtfSubmitLogRepositoryTest.java
  src/test/java/keeper/project/homepage/ctf/repository/CtfTestHelper.java
  src/test/java/keeper/project/homepage/ctf/service/CtfServiceTest.java
  src/test/java/keeper/project/homepage/ctf/service/CtfTeamServiceTest.java
  src/test/java/keeper/project/homepage/util/service/CtfUtilServiceTest.java
Labels: ❤️ refactor, ✏️ test, 📑 chore

#441 Feature/#438 exception advice을 개선하고 exception 예외 메시지를 의미있게 변경
  src/main/java/keeper/project/homepage/ExceptionAdvice.java
  src/main/java/keeper/project/homepage/about/exception/AboutExceptionAdvice.java
  src/main/java/keeper/project/homepage/attendance/exception/AttendanceExceptionAdvice.java
  src/main/java/keeper/project/homepage/attendance/service/AttendanceService.java
  src/main/java/keeper/project/homepage/attendance/service/GameService.java
  src/main/java/keeper/project/homepage/clerk/exception/ClerkExceptionAdvice.java
  src/main/java/keeper/project/homepage/ctf/exception/CtfExceptionAdvice.java
  src/main/java/keeper/project/homepage/ctf/service/CtfAdminService.java
  src/main/java/keeper/project/homepage/election/exception/ElectionExceptionAdvice.java
  src/main/java/keeper/project/homepage/library/exception/BookExceptionAdvice.java
  src/main/java/keeper/project/homepage/library/service/BookManageService.java
  src/main/java/keeper/project/homepage/member/exception/CustomMemberNotFoundException.java
  src/main/java/keeper/project/homepage/member/exception/MemberExceptionAdvice.java
  src/main/java/keeper/project/homepage/member/service/AdminMemberUtilService.java
  src/main/java/keeper/project/homepage/member/service/MemberService.java
  src/main/java/keeper/project/homepage/member/service/MemberUtilService.java
  src/main/java/keeper/project/homepage/point/exception/PointExceptionAdvice.java
  src/main/java/keeper/project/homepage/point/service/PointLogService.java
  src/main/java/keeper/project/homepage/posting/exception/PostingExceptionAdvice.java
  src/main/java/keeper/project/homepage/posting/service/AdminPostingService.java
  src/main/java/keeper/project/homepage/posting/service/PostingService.java
  src/main/java/keeper/project/homepage/sign/exception/SignExceptionAdvice.java
  src/main/java/keeper/project/homepage/study/exception/StudyExceptionAdvice.java
  src/main/java/keeper/project/homepage/study/service/StudyService.java
  src/main/java/keeper/project/homepage/systemadmin/exception/CustomClerkInaccessibleJobException.java
  src/main/java/keeper/project/homepage/systemadmin/exception/SystemAdminExceptionAdvice.java
  src/main/java/keeper/project/homepage/systemadmin/service/SystemAdminService.java
  src/main/java/keeper/project/homepage/util/exception/ExceptionAdviceUtil.java
  src/main/java/keeper/project/homepage/util/exception/UtilExceptionAdvice.java
  src/main/resources/exception.properties
  src/test/java/keeper/project/homepage/ApiControllerTestSetUp.java
  src/test/java/keeper/project/homepage/member/controller/MemberControllerFindPostingTest.java
  src/test/java/keeper/project/homepage/member/controller/MemberControllerTest.java
  src/test/java/keeper/project/homepage/member/controller/MemberUpdateControllerTest.java
  src/test/java/keeper/project/homepage/posting/controller/AdminCommentControllerTest.java
  src/test/java/keeper/project/homepage/posting/controller/CommentControllerTest.java
  src/test/java/keeper/project/homepage/sign/controller/SignInControllerTest.java
  src/test/java/keeper/project/homepage/study/controller/StudyControllerTest.java
  src/test/java/keeper/project/homepage/systemadmin/service/SystemAdminServiceTest.java
  src/test/java/keeper/project/homepage/util/controller/AdminBadgeControllerTest.java
Labels: 📑 chore, enhancement

#442 Feature/#439 ctf 코드를 개선한다
  src/main/java/keeper/project/homepage/ctf/service/CtfAdminService.java
  src/main/java/keeper/project/homepage/ctf/service/CtfChallengeService.java
  src/main/java/keeper/project/homepage/ctf/service/CtfExtraDataService.java
  src/main/java/keeper/project/homepage/ctf/service/CtfRankingService.java
  src/main/java/keeper/project/homepage/ctf/service/CtfTeamService.java
Labels: enhancement

#445 Feature/#444 회원 총 출석일수 컬럼을 백엔드 코드에도 추가 적용한다
  src/main/java/keeper/project/homepage/member/entity/MemberEntity.java
Labels: 🛠 bug

#447 Feature/#443 테스트 할 때 embedded redis를 사용하도록 변경
  build.gradle
  src/main/java/keeper/project/homepage/config/redis/RedisConfig.java
  src/main/java/keeper/project/homepage/config/redis/TestRedisConfiguration.java
  src/test/resources/config/application.properties
Labels: ✏️ test, 📑 chore, enhancement

#449 Feature/readme 업데이트
  CONTRIBUTING.md
  README.md
Labels: 📄 docs

#450 chore: QueryDSL 추가
  build.gradle
Labels: 📑 chore

#452 Feature/#451 embedded redis 적용 철회
  build.gradle
  src/main/java/keeper/project/homepage/config/redis/RedisConfig.java
  src/main/java/keeper/project/homepage/config/redis/TestRedisConfiguration.java
  src/test/resources/config/application.properties
Labels: 🛠 bug

#456 Feature/#453 출석 관련 코드 개선 및 수정
  src/main/java/keeper/project/homepage/about/dto/AttendanceDto.java
  src/main/java/keeper/project/homepage/about/dto/AttendanceResultDto.java
  src/main/java/keeper/project/homepage/attendance/controller/AttendanceController.java
  src/main/java/keeper/project/homepage/attendance/entity/AttendanceEntity.java
  src/main/java/keeper/project/homepage/attendance/service/AttendanceService.java
  src/main/java/keeper/project/homepage/member/repository/MemberRepository.java
  src/main/java/keeper/project/homepage/util/redis/RedisUtil.java
  src/test/java/keeper/project/homepage/ApiControllerTestHelper.java
  src/test/java/keeper/project/homepage/attendance/service/AttendanceServiceTest.java
  src/test/java/keeper/project/homepage/member/service/MemberServiceTestSetup.java
Labels: 🛠 bug, enhancement
