Repository KEEPER31337/Homepage-Back, pull requests merged in 2022-02, with the labels that each got.

#92 Feature/출석 기록 update
  src/docs/asciidoc/attendance.adoc
  src/main/java/keeper/project/homepage/controller/attendance/AttendanceController.java
  src/main/java/keeper/project/homepage/dto/attendance/AttendanceDto.java
  src/main/java/keeper/project/homepage/entity/attendance/AttendanceEntity.java
  src/main/java/keeper/project/homepage/exception/CustomAttendanceException.java
  src/main/java/keeper/project/homepage/exception/ExceptionAdvice.java
  src/main/java/keeper/project/homepage/repository/attendance/AttendanceRepository.java
  src/main/java/keeper/project/homepage/service/attendance/AttendanceService.java
  src/main/resources/exception.properties
  src/main/resources/exception_en.properties
  src/main/resources/exception_ko.properties
  src/test/java/keeper/project/homepage/ApiControllerTestSetUp.java
  src/test/java/keeper/project/homepage/controller/attendance/AttendanceControllerTest.java
Labels: feat, docs, test

#102 Feature/메인페이지 헤더
  src/main/java/keeper/project/homepage/controller/posting/CategoryController.java
  src/main/java/keeper/project/homepage/dto/result/CategoryResult.java
  src/main/java/keeper/project/homepage/entity/posting/CategoryEntity.java
  src/main/java/keeper/project/homepage/repository/posting/CategoryRepository.java
  src/main/java/keeper/project/homepage/service/posting/CategoryService.java
  src/test/java/keeper/project/homepage/controller/posting/CategoryControllerTest.java
Labels: feat, test

#103 Feature/임시저장 게시물 확인
  src/main/java/keeper/project/homepage/controller/member/MemberController.java
  src/main/java/keeper/project/homepage/controller/posting/PostingController.java
  src/main/java/keeper/project/homepage/dto/posting/PostingDto.java
  src/main/java/keeper/project/homepage/entity/member/MemberEntity.java
  src/main/java/keeper/project/homepage/repository/posting/PostingRepository.java
  src/main/java/keeper/project/homepage/service/member/MemberService.java
  src/main/java/keeper/project/homepage/service/posting/PostingService.java
  src/test/java/keeper/project/homepage/controller/member/MemberControllerFindPostingTest.java
  src/test/java/keeper/project/homepage/controller/posting/PostingControllerTest.java
Labels: feat

#104 Feature/내 정보 수정
  src/docs/asciidoc/keeper.adoc
  src/docs/asciidoc/member.adoc
  src/main/java/keeper/project/homepage/common/FileConversion.java
  src/main/java/keeper/project/homepage/common/ImageCenterCrop.java
  src/main/java/keeper/project/homepage/common/ImageFormatChecking.java
  src/main/java/keeper/project/homepage/common/ImageProcessing.java
  src/main/java/keeper/project/homepage/common/ImageResize.java
  src/main/java/keeper/project/homepage/controller/member/MemberController.java
  src/main/java/keeper/project/homepage/controller/posting/PostingController.java
  src/main/java/keeper/project/homepage/dto/member/MemberDto.java
  src/main/java/keeper/project/homepage/dto/member/MemberJobDto.java
  src/main/java/keeper/project/homepage/dto/member/MemberRankDto.java
  src/main/java/keeper/project/homepage/dto/member/MemberTypeDto.java
  src/main/java/keeper/project/homepage/entity/member/MemberEntity.java
  src/main/java/keeper/project/homepage/entity/member/MemberJobEntity.java
  src/main/java/keeper/project/homepage/entity/member/MemberRankEntity.java
  src/main/java/keeper/project/homepage/entity/member/MemberTypeEntity.java
  src/main/java/keeper/project/homepage/entity/posting/PostingEntity.java
  src/main/java/keeper/project/homepage/repository/member/MemberHasMemberJobRepository.java
  src/main/java/keeper/project/homepage/repository/member/MemberRankRepository.java
  src/main/java/keeper/project/homepage/repository/member/MemberTypeRepository.java
  src/main/java/keeper/project/homepage/service/FileService.java
  src/main/java/keeper/project/homepage/service/ThumbnailService.java
  src/main/java/keeper/project/homepage/service/member/MemberService.java
  src/main/java/keeper/project/homepage/service/posting/CommentService.java
  src/test/java/keeper/project/homepage/controller/member/MemberControllerTest.java
  src/test/java/keeper/project/homepage/controller/posting/PostingControllerTest.java
  src/test/java/keeper/project/homepage/service/ThumbnailServiceTest.java
Labels: feat, docs, test

#105 Feature/친구 관리
  src/main/java/keeper/project/homepage/controller/member/MemberController.java
  src/main/java/keeper/project/homepage/dto/member/MemberDto.java
  src/main/java/keeper/project/homepage/entity/member/FriendEntity.java
  src/main/java/keeper/project/homepage/entity/member/MemberEntity.java
  src/main/java/keeper/project/homepage/repository/member/FriendRepository.java
  src/main/java/keeper/project/homepage/service/member/MemberService.java
  src/test/java/keeper/project/homepage/ApiControllerTestSetUp.java
  src/test/java/keeper/project/homepage/controller/member/MemberControllerTest.java
Labels: feat, test

#106 Feature/다른회원관리 포인트선물
  src/main/java/keeper/project/homepage/controller/member/MemberController.java
  src/main/java/keeper/project/homepage/dto/member/MemberDto.java
  src/main/java/keeper/project/homepage/dto/request/PointTransferRequest.java
  src/main/java/keeper/project/homepage/dto/result/PointTransferResult.java
  src/main/java/keeper/project/homepage/entity/member/FriendEntity.java
  src/main/java/keeper/project/homepage/entity/member/MemberEntity.java
  src/main/java/keeper/project/homepage/entity/member/MemberHasMemberJobEntity.java
  src/main/java/keeper/project/homepage/exception/CustomTransferPointLackException.java
  src/main/java/keeper/project/homepage/exception/ExceptionAdvice.java
  src/main/java/keeper/project/homepage/service/member/MemberService.java
  src/main/resources/exception.properties
  src/test/java/keeper/project/homepage/controller/member/MemberControllerTest.java
Labels: feat, test

#107 fix : deletePosting test시 오류 수정
  src/test/java/keeper/project/homepage/controller/posting/PostingControllerTest.java
Labels: fix

#108 fix : categoryResult test 오류 수정
  src/main/java/keeper/project/homepage/dto/result/CategoryResult.java
  src/main/java/keeper/project/homepage/repository/posting/CategoryRepository.java
  src/test/java/keeper/project/homepage/controller/posting/CategoryControllerTest.java
Labels: fix

#110 feat: 내 출석 정보 확인 등수 추가
  src/main/java/keeper/project/homepage/entity/attendance/AttendanceEntity.java
  src/main/java/keeper/project/homepage/service/attendance/AttendanceService.java
  src/test/java/keeper/project/homepage/ApiControllerTestSetUp.java
  src/test/java/keeper/project/homepage/controller/attendance/AttendanceControllerTest.java
Labels: feat, test

#109 Feature/다른회원관리 정보조회
  src/main/java/keeper/project/homepage/controller/member/MemberController.java
  src/main/java/keeper/project/homepage/dto/result/OtherMemberInfoResult.java
  src/main/java/keeper/project/homepage/service/member/MemberService.java
  src/test/java/keeper/project/homepage/controller/member/MemberControllerTest.java
Labels: feat, test

#115 Feature/썸네일 수정
  src/main/java/keeper/project/homepage/controller/member/MemberController.java
  src/main/java/keeper/project/homepage/dto/member/MemberDto.java
  src/main/java/keeper/project/homepage/service/FileService.java
  src/main/java/keeper/project/homepage/service/member/MemberService.java
  src/test/java/keeper/project/homepage/controller/member/MemberControllerFindPostingTest.java
  src/test/java/keeper/project/homepage/controller/member/MemberControllerTest.java
Labels: fix

#116 Feature/선택한 도서 정보 전달
  src/docs/asciidoc/librarymain.adoc
  src/main/java/keeper/project/homepage/controller/library/LibraryMainController.java
  src/main/java/keeper/project/homepage/service/library/LibraryMainService.java
  src/test/java/keeper/project/homepage/controller/library/LibraryMainControllerTest.java
Labels: feat

#119 docs : 카테고리 불러오기 API 문서 작성
  src/docs/asciidoc/category.adoc
Labels: docs

#117 Feature/게시판 fix
  src/main/java/keeper/project/homepage/controller/posting/PostingController.java
  src/main/java/keeper/project/homepage/service/posting/PostingService.java
  src/test/java/keeper/project/homepage/controller/posting/PostingControllerTest.java
Labels: fix, refactor

#121 Feature/도서 반납 기능
  src/docs/asciidoc/bookmanage.adoc
  src/main/java/keeper/project/homepage/controller/library/BookManageController.java
  src/main/java/keeper/project/homepage/dto/BookBorrowDto.java
  src/main/java/keeper/project/homepage/entity/library/BookBorrowEntity.java
  src/main/java/keeper/project/homepage/repository/library/BookBorrowRepository.java
  src/main/java/keeper/project/homepage/service/library/BookManageService.java
  src/test/java/keeper/project/homepage/ApiControllerTestSetUp.java
  src/test/java/keeper/project/homepage/controller/library/BookManageControllerTest.java
Labels: feat

#124 Feature/최근 도서 오류 수정
  src/main/java/keeper/project/homepage/controller/library/LibraryMainController.java
  src/main/java/keeper/project/homepage/service/library/LibraryMainService.java
  src/test/java/keeper/project/homepage/controller/library/LibraryMainControllerTest.java
Labels: feat, fix

#122 Feature/연체 도서 표시
  src/docs/asciidoc/bookmanage.adoc
  src/main/java/keeper/project/homepage/controller/library/BookManageController.java
  src/main/java/keeper/project/homepage/repository/library/BookBorrowRepository.java
  src/main/java/keeper/project/homepage/service/library/BookManageService.java
  src/test/java/keeper/project/homepage/ApiControllerTestSetUp.java
  src/test/java/keeper/project/homepage/controller/library/BookManageControllerTest.java
Labels: feat

#118 Feature/댓글 fix
  src/main/java/keeper/project/homepage/common/ImageCenterCrop.java
  src/main/java/keeper/project/homepage/common/ImageFormatChecking.java
  src/main/java/keeper/project/homepage/common/ImageProcessing.java
  src/main/java/keeper/project/homepage/common/ImageResize.java
  src/main/java/keeper/project/homepage/controller/posting/CommentController.java
  src/main/java/keeper/project/homepage/controller/posting/PostingController.java
  src/main/java/keeper/project/homepage/dto/posting/CommentDto.java
  src/main/java/keeper/project/homepage/entity/posting/CommentEntity.java
  src/main/java/keeper/project/homepage/exception/CustomNumberOverflowException.java
  src/main/java/keeper/project/homepage/exception/ExceptionAdvice.java
  src/main/java/keeper/project/homepage/exception/file/CustomFileDeleteFailedException.java
  src/main/java/keeper/project/homepage/exception/file/CustomFileEntityNotFoundException.java
  src/main/java/keeper/project/homepage/exception/file/CustomFileNotFoundException.java
  src/main/java/keeper/project/homepage/exception/file/CustomFileTransferFailedException.java
  src/main/java/keeper/project/homepage/exception/file/CustomImageFormatException.java
  src/main/java/keeper/project/homepage/exception/file/CustomImageIOException.java
  src/main/java/keeper/project/homepage/exception/file/CustomThumbnailEntityNotFoundException.java
  src/main/java/keeper/project/homepage/exception/member/CustomMemberDuplicateException.java
  src/main/java/keeper/project/homepage/exception/member/CustomMemberEmptyFieldException.java
  src/main/java/keeper/project/homepage/exception/member/CustomMemberInfoNotFoundException.java
  src/main/java/keeper/project/homepage/exception/member/CustomMemberNotFoundException.java
  src/main/java/keeper/project/homepage/exception/posting/CustomCommentEmptyFieldException.java
  src/main/java/keeper/project/homepage/exception/posting/CustomCommentNotFoundException.java
  src/main/java/keeper/project/homepage/service/FileService.java
  src/main/java/keeper/project/homepage/service/ThumbnailService.java
  src/main/java/keeper/project/homepage/service/attendance/AttendanceService.java
  src/main/java/keeper/project/homepage/service/member/CustomMemberDetailService.java
  src/main/java/keeper/project/homepage/service/member/MemberService.java
  src/main/java/keeper/project/homepage/service/posting/CommentService.java
  src/main/resources/exception.properties
  src/main/resources/exception_ko.properties
  src/test/java/keeper/project/homepage/controller/member/MemberControllerTest.java
  src/test/java/keeper/project/homepage/controller/posting/CommentControllerTest.java
  src/test/java/keeper/project/homepage/controller/posting/PostingControllerTest.java
  src/test/java/keeper/project/homepage/controller/sign/SignInControllerTest.java
  src/test/java/keeper/project/homepage/repository/posting/CommentRepositoryTest.java
  src/test/java/keeper/project/homepage/service/ThumbnailServiceTest.java
  src/test/java/keeper/project/homepage/service/posting/CommentServiceTest.java
Labels: feat, fix, refactor

#126 Feature/api 자동 배포 시스템
  .gitignore
  build.gradle
  docker/app.dockerfile
  docker/application.properties
  docker/docker-compose.yml
  docker/dockerfile/app.dockerfile
  docker/dockerfile/db.dockerfile
  docker/entrypoint.sh
  docker/env.example
  docker/readme.md
  docker/run.bat
  docker/run.sh
Labels: refactor

#128 Feature/메인페이지 소개페이지
  src/main/java/keeper/project/homepage/controller/etc/AboutContentController.java
  src/main/java/keeper/project/homepage/controller/etc/AboutSubtitleController.java
  src/main/java/keeper/project/homepage/controller/etc/AboutTitleController.java
  src/main/java/keeper/project/homepage/dto/etc/StaticWriteContentDto.java
  src/main/java/keeper/project/homepage/dto/etc/StaticWriteSubtitleImageDto.java
  src/main/java/keeper/project/homepage/dto/result/StaticWriteContentResult.java
  src/main/java/keeper/project/homepage/dto/result/StaticWriteSubtitleImageResult.java
  src/main/java/keeper/project/homepage/dto/result/StaticWriteTitleResult.java
  src/main/java/keeper/project/homepage/entity/etc/StaticWriteContentEntity.java
  src/main/java/keeper/project/homepage/entity/etc/StaticWriteSubtitleImageEntity.java
  src/main/java/keeper/project/homepage/repository/etc/StaticWriteTitleRepository.java
  src/main/java/keeper/project/homepage/service/etc/AboutContentService.java
  src/main/java/keeper/project/homepage/service/etc/AboutService.java
  src/main/java/keeper/project/homepage/service/etc/AboutSubtitleService.java
  src/main/java/keeper/project/homepage/service/etc/AboutTitleService.java
  src/test/java/keeper/project/homepage/ApiControllerTestSetUp.java
  src/test/java/keeper/project/homepage/controller/etc/AboutContentControllerTest.java
  src/test/java/keeper/project/homepage/controller/etc/AboutSubtitleControllerTest.java
  src/test/java/keeper/project/homepage/controller/etc/AboutTitleControllerTest.java
Labels: feat, test

#130 Feature/도서 반납 로직 수정
  src/main/java/keeper/project/homepage/exception/ExceptionAdvice.java
  src/main/java/keeper/project/homepage/exception/library/CustomBookBorrowNotFoundException.java
  src/main/java/keeper/project/homepage/exception/library/CustomBookNotFoundException.java
  src/main/java/keeper/project/homepage/exception/library/CustomBookOverTheMaxException.java
  src/main/java/keeper/project/homepage/repository/library/BookBorrowRepository.java
  src/main/java/keeper/project/homepage/service/library/BookManageService.java
  src/main/resources/exception.properties
  src/main/resources/exception_en.properties
  src/main/resources/exception_ko.properties
  src/test/java/keeper/project/homepage/controller/library/BookManageControllerTest.java
Labels: feat, fix

#133 Feature/게시판 여러 오류 수정
  src/docs/asciidoc/posting.adoc
  src/main/java/keeper/project/homepage/controller/posting/PostingController.java
  src/main/java/keeper/project/homepage/dto/posting/LikeAndDislikeDto.java
  src/main/java/keeper/project/homepage/dto/result/PostingResult.java
  src/main/java/keeper/project/homepage/entity/FileEntity.java
  src/main/java/keeper/project/homepage/entity/posting/PostingEntity.java
  src/main/java/keeper/project/homepage/service/posting/PostingService.java
  src/test/java/keeper/project/homepage/controller/posting/PostingControllerTest.java
Labels: feat, fix, docs, test

#136 Feature/도서관 response 단일화
  src/main/java/keeper/project/homepage/controller/library/BookManageController.java
  src/main/java/keeper/project/homepage/controller/library/LibraryMainController.java
  src/test/java/keeper/project/homepage/controller/library/BookManageControllerTest.java
Labels: refactor

#137 fix : 출석 생성시 오류 수정
  src/main/java/keeper/project/homepage/service/attendance/AttendanceService.java
Labels: fix

#138 Feature/로그인시 thumbnail id 추가
  src/main/java/keeper/project/homepage/controller/posting/PostingController.java
  src/main/java/keeper/project/homepage/dto/member/MemberDto.java
  src/main/java/keeper/project/homepage/dto/posting/CommentDto.java
  src/main/java/keeper/project/homepage/dto/posting/PostingDto.java
  src/main/java/keeper/project/homepage/entity/ThumbnailEntity.java
  src/main/java/keeper/project/homepage/entity/posting/CommentEntity.java
  src/main/java/keeper/project/homepage/entity/posting/PostingEntity.java
  src/main/java/keeper/project/homepage/service/posting/CommentService.java
  src/main/java/keeper/project/homepage/service/posting/PostingService.java
  src/test/java/keeper/project/homepage/controller/member/MemberControllerTest.java
  src/test/java/keeper/project/homepage/controller/posting/CommentControllerTest.java
  src/test/java/keeper/project/homepage/controller/posting/PostingControllerTest.java
  src/test/java/keeper/project/homepage/controller/sign/SignInControllerTest.java
  src/test/java/keeper/project/homepage/repository/member/MemberHasCommentDislikeRepositoryTest.java
  src/test/java/keeper/project/homepage/repository/member/MemberHasCommentLikeRepositoryTest.java
  src/test/java/keeper/project/homepage/repository/posting/CommentRepositoryTest.java
  src/test/java/keeper/project/homepage/service/ThumbnailServiceTest.java
  src/test/java/keeper/project/homepage/service/member/MemberHasCommentDislikeServiceTest.java
  src/test/java/keeper/project/homepage/service/member/MemberHasCommentLikeServiceTest.java
  src/test/java/keeper/project/homepage/service/posting/CommentServiceTest.java
Labels: fix

#131 Feature/메인페이지 헤더 관리
  src/docs/asciidoc/category.adoc
  src/docs/asciidoc/keeper.adoc
  src/main/java/keeper/project/homepage/controller/posting/CategoryController.java
  src/main/java/keeper/project/homepage/dto/posting/CategoryDto.java
  src/main/java/keeper/project/homepage/entity/posting/CategoryEntity.java
  src/main/java/keeper/project/homepage/exception/ExceptionAdvice.java
  src/main/java/keeper/project/homepage/exception/posting/CustomAccessRootCategoryException.java
  src/main/java/keeper/project/homepage/exception/posting/CustomCategoryNotFoundException.java
  src/main/java/keeper/project/homepage/exception/posting/CustomParentCategoryNotFoundException.java
  src/main/java/keeper/project/homepage/service/posting/CategoryService.java
  src/main/resources/exception.properties
  src/test/java/keeper/project/homepage/controller/posting/CategoryControllerTest.java
Labels: feat, docs, test

#134 Feature/멤버 리팩토링 및 수정
  src/docs/asciidoc/member.adoc
  src/docs/asciidoc/member_info.adoc
  src/docs/asciidoc/member_posting.adoc
  src/docs/asciidoc/member_update.adoc
  src/main/java/keeper/project/homepage/controller/member/MemberController.java
  src/main/java/keeper/project/homepage/exception/ExceptionAdvice.java
  src/main/java/keeper/project/homepage/service/member/MemberService.java
  src/main/resources/exception.properties
  src/test/java/keeper/project/homepage/controller/member/MemberControllerFindPostingTest.java
  src/test/java/keeper/project/homepage/controller/member/MemberControllerTest.java
  src/test/java/keeper/project/homepage/controller/member/MemberControllerTestSetup.java
  src/test/java/keeper/project/homepage/controller/member/MemberUpdateControllerTest.java
Labels: refactor, docs, test

#139 Feature/출석부 게임 기능
  src/docs/asciidoc/game.adoc
  src/docs/asciidoc/keeper.adoc
  src/main/java/keeper/project/homepage/controller/attendance/GameController.java
  src/main/java/keeper/project/homepage/dto/attendance/GameInfoDto.java
  src/main/java/keeper/project/homepage/dto/attendance/RouletteDto.java
  src/main/java/keeper/project/homepage/entity/attendance/GameEntity.java
  src/main/java/keeper/project/homepage/repository/attendance/GameRepository.java
  src/main/java/keeper/project/homepage/service/attendance/GameService.java
  src/test/java/keeper/project/homepage/controller/attendance/GameControllerTest.java
Labels: feat, docs, test

#141 Feature/내정보관리 멤버정보조회 일반정보
  src/main/java/keeper/project/homepage/controller/member/MemberController.java
  src/main/java/keeper/project/homepage/service/member/MemberService.java
  src/test/java/keeper/project/homepage/controller/member/MemberControllerTest.java
Labels: feat, test

#144 Feature/출석부 수정 요청
  src/main/java/keeper/project/homepage/controller/attendance/AttendanceController.java
  src/main/java/keeper/project/homepage/dto/attendance/AttendanceForListDto.java
  src/main/java/keeper/project/homepage/dto/attendance/AttendancePointDto.java
  src/main/java/keeper/project/homepage/entity/attendance/AttendanceEntity.java
  src/main/java/keeper/project/homepage/repository/attendance/AttendanceRepository.java
  src/main/java/keeper/project/homepage/service/attendance/AttendanceService.java
  src/main/java/keeper/project/homepage/service/util/AuthService.java
  src/test/java/keeper/project/homepage/controller/attendance/AttendanceControllerTest.java
Labels: feat, fix

#146 fix: 이전버전으로 변경
  docker/docker-compose.yml
  docker/dockerfile/app.dockerfile
  docker/run.bat
  docker/run.sh
Labels: fix

#145 Feature/댓글 리팩토링 및 수정
  src/docs/asciidoc/commentAdmin.adoc
  src/main/java/keeper/project/homepage/admin/controller/posting/AdminCommentController.java
  src/main/java/keeper/project/homepage/controller/posting/CommentController.java
  src/main/java/keeper/project/homepage/dto/posting/CommentDto.java
  src/main/java/keeper/project/homepage/entity/posting/CommentEntity.java
  src/main/java/keeper/project/homepage/service/posting/CommentService.java
  src/test/java/keeper/project/homepage/ApiControllerTestSetUp.java
  src/test/java/keeper/project/homepage/controller/posting/CommentControllerTest.java
  src/test/java/keeper/project/homepage/repository/member/MemberHasCommentDislikeRepositoryTest.java
  src/test/java/keeper/project/homepage/repository/member/MemberHasCommentLikeRepositoryTest.java
  src/test/java/keeper/project/homepage/repository/posting/CommentRepositoryTest.java
  src/test/java/keeper/project/homepage/service/member/MemberHasCommentDislikeServiceTest.java
  src/test/java/keeper/project/homepage/service/member/MemberHasCommentLikeServiceTest.java
  src/test/java/keeper/project/homepage/service/posting/CommentServiceTest.java
Labels: fix

#147 Feature/출석부 수정사항 1개
  src/main/java/keeper/project/homepage/controller/attendance/AttendanceController.java
  src/main/java/keeper/project/homepage/dto/attendance/AttendanceForListDto.java
  src/main/java/keeper/project/homepage/dto/attendance/AttendanceResultDto.java
  src/main/java/keeper/project/homepage/entity/attendance/AttendanceEntity.java
  src/main/java/keeper/project/homepage/service/attendance/AttendanceService.java
  src/test/java/keeper/project/homepage/controller/attendance/AttendanceControllerTest.java
Labels: fix, test

#148 Feature/api 문서 작성
  src/docs/asciidoc/about.adoc
  src/docs/asciidoc/aboutAdmin.adoc
  src/docs/asciidoc/category.adoc
  src/docs/asciidoc/keeper.adoc
  src/test/java/keeper/project/homepage/controller/etc/AboutContentControllerTest.java
  src/test/java/keeper/project/homepage/controller/etc/AboutSubtitleControllerTest.java
  src/test/java/keeper/project/homepage/controller/etc/AboutTitleControllerTest.java
Labels: docs, test

#150 feat: 출석부 정보에 memberId 포함해서 전달
  src/main/java/keeper/project/homepage/dto/attendance/AttendanceResultDto.java
Labels: feat

#152 Feature/댓글 조회 시 좋아요, 싫어요 확인
  src/docs/asciidoc/comment.adoc
  src/main/java/keeper/project/homepage/controller/posting/CommentController.java
  src/main/java/keeper/project/homepage/dto/posting/CommentDto.java
  src/main/java/keeper/project/homepage/entity/member/MemberHasCommentDislikeEntity.java
  src/main/java/keeper/project/homepage/service/posting/CommentService.java
  src/test/java/keeper/project/homepage/ApiControllerTestSetUp.java
  src/test/java/keeper/project/homepage/controller/posting/CommentControllerTest.java
  src/test/java/keeper/project/homepage/service/posting/CommentServiceTest.java
Labels: feat, fix, docs

#149 Feature/도서 표지 카테고리 추가
  src/main/java/keeper/project/homepage/admin/controller/library/BookManageController.java
  src/main/java/keeper/project/homepage/admin/service/library/BookManageService.java
  src/main/java/keeper/project/homepage/dto/library/BookBorrowDto.java
  src/main/java/keeper/project/homepage/dto/library/BookDto.java
  src/main/java/keeper/project/homepage/entity/library/BookDepartmentEntity.java
  src/main/java/keeper/project/homepage/entity/library/BookEntity.java
  src/main/java/keeper/project/homepage/exception/ExceptionAdvice.java
  src/main/java/keeper/project/homepage/exception/library/CustomBookDepartmentNotFoundException.java
  src/main/java/keeper/project/homepage/repository/library/BookDepartmentRepository.java
  src/main/java/keeper/project/homepage/user/controller/library/LibraryMainController.java
  src/main/java/keeper/project/homepage/user/service/library/LibraryMainService.java
  src/main/resources/exception.properties
  src/main/resources/exception_en.properties
  src/main/resources/exception_ko.properties
  src/test/java/keeper/project/homepage/ApiControllerTestSetUp.java
  src/test/java/keeper/project/homepage/controller/library/BookManageControllerTest.java
Labels: feat, fix, refactor

#142 Feature/내정보관리 포인트관리
  src/docs/asciidoc/keeper.adoc
  src/docs/asciidoc/pointLog.adoc
  src/main/java/keeper/project/homepage/controller/member/MemberController.java
  src/main/java/keeper/project/homepage/dto/point/request/PointGiftLogRequest.java
  src/main/java/keeper/project/homepage/dto/point/request/PointLogRequest.java
  src/main/java/keeper/project/homepage/dto/point/result/PointGiftLogResult.java
  src/main/java/keeper/project/homepage/dto/point/result/PointLogResult.java
  src/main/java/keeper/project/homepage/dto/request/PointTransferRequest.java
  src/main/java/keeper/project/homepage/dto/result/PointTransferResult.java
  src/main/java/keeper/project/homepage/entity/point/PointLogEntity.java
  src/main/java/keeper/project/homepage/exception/CustomPointLogRequestNullException.java
  src/main/java/keeper/project/homepage/exception/ExceptionAdvice.java
  src/main/java/keeper/project/homepage/repository/point/PointLogRepository.java
  src/main/java/keeper/project/homepage/service/member/MemberService.java
  src/main/java/keeper/project/homepage/service/util/AuthService.java
  src/main/java/keeper/project/homepage/user/controller/point/PointLogController.java
  src/main/java/keeper/project/homepage/user/service/point/PointLogService.java
  src/main/resources/exception.properties
  src/test/java/keeper/project/homepage/ApiControllerTestSetUp.java
  src/test/java/keeper/project/homepage/controller/member/MemberControllerTest.java
  src/test/java/keeper/project/homepage/controller/point/PointLogControllerTest.java
  src/test/java/keeper/project/homepage/service/point/PointLogServiceTest.java
Labels: feat, fix, test

#153 fix : PostingEntity 반환해주는 부분 총 갯수 반환하도록 수정
  src/main/java/keeper/project/homepage/entity/posting/PostingEntity.java
  src/main/java/keeper/project/homepage/repository/posting/PostingRepository.java
  src/main/java/keeper/project/homepage/service/posting/PostingService.java
  src/test/java/keeper/project/homepage/controller/posting/PostingControllerTest.java
Labels: fix

#154 Feature/게시물 관리자 기능
  src/docs/asciidoc/postingAdmin.adoc
  src/main/java/keeper/project/homepage/admin/controller/posting/AdminPostingController.java
  src/main/java/keeper/project/homepage/admin/service/posting/AdminPostingService.java
  src/main/java/keeper/project/homepage/controller/posting/PostingController.java
  src/test/java/keeper/project/homepage/controller/posting/PostingControllerTest.java
Labels: feat, docs, test

#155 Feature/댓글 조회 기능 수정
  src/docs/asciidoc/admin.adoc
  src/docs/asciidoc/keeper.adoc
  src/docs/asciidoc/posting/comment.adoc
  src/docs/asciidoc/posting/commentAdmin.adoc
  src/main/java/keeper/project/homepage/repository/posting/CommentRepository.java
  src/main/java/keeper/project/homepage/repository/posting/CommentSpec.java
  src/main/java/keeper/project/homepage/service/posting/CommentService.java
  src/test/java/keeper/project/homepage/ApiControllerTestHelper.java
  src/test/java/keeper/project/homepage/controller/posting/CommentControllerTest.java
Labels: refactor, docs, test

#143 Feature/회원 탈퇴
  .jqwik-database
  src/docs/asciidoc/member.adoc
  src/docs/asciidoc/member_info.adoc
  src/main/java/keeper/project/homepage/controller/member/MemberController.java
  src/main/java/keeper/project/homepage/entity/ThumbnailEntity.java
  src/main/java/keeper/project/homepage/entity/member/FriendEntity.java
  src/main/java/keeper/project/homepage/entity/member/MemberEntity.java
  src/main/java/keeper/project/homepage/entity/posting/CommentEntity.java
  src/main/java/keeper/project/homepage/entity/posting/PostingEntity.java
  src/main/java/keeper/project/homepage/exception/ExceptionAdvice.java
  src/main/java/keeper/project/homepage/exception/member/CustomAccountDeleteFailedException.java
  src/main/java/keeper/project/homepage/repository/library/BookBorrowRepository.java
  src/main/java/keeper/project/homepage/repository/member/MemberHasPostingDislikeRepository.java
  src/main/java/keeper/project/homepage/repository/member/MemberHasPostingLikeRepository.java
  src/main/java/keeper/project/homepage/repository/point/PointLogRepository.java
  src/main/java/keeper/project/homepage/repository/posting/CommentRepository.java
  src/main/java/keeper/project/homepage/repository/posting/PostingRepository.java
  src/main/java/keeper/project/homepage/service/member/MemberDeleteService.java
  src/main/java/keeper/project/homepage/service/member/MemberService.java
  src/main/resources/exception.properties
  src/test/java/keeper/project/homepage/controller/member/MemberControllerTest.java
  src/test/java/keeper/project/homepage/service/member/MemberServiceTest.java
  src/test/java/keeper/project/homepage/service/member/MemberServiceTestSetup.java
Labels: feat, docs, test

#160 fix: 랭킹 수정사항
  src/docs/asciidoc/rank.adoc
  src/main/java/keeper/project/homepage/controller/attendance/RankController.java
  src/main/java/keeper/project/homepage/dto/rank/RankResult.java
  src/main/java/keeper/project/homepage/service/attendance/RankService.java
  src/test/java/keeper/project/homepage/ApiControllerTestSetUp.java
  src/test/java/keeper/project/homepage/controller/attendance/RankControllerTest.java
Labels: fix, docs, test

#159 Feature/헤더기능 리팩토링
  src/docs/asciidoc/admin.adoc
  src/docs/asciidoc/categoryAdmin.adoc
  src/docs/asciidoc/keeper.adoc
  src/docs/asciidoc/posting/category.adoc
  src/docs/asciidoc/posting/categoryAdmin.adoc
  src/main/java/keeper/project/homepage/admin/controller/posting/AdminCategoryController.java
  src/main/java/keeper/project/homepage/admin/service/posting/AdminCategoryService.java
  src/main/java/keeper/project/homepage/controller/posting/CategoryController.java
  src/main/java/keeper/project/homepage/dto/posting/category/reqeust/CategoryRequest.java
  src/main/java/keeper/project/homepage/dto/posting/category/result/CategoryResult.java
  src/main/java/keeper/project/homepage/dto/posting/category/result/CategoryWithChildResult.java
  src/main/java/keeper/project/homepage/entity/posting/CategoryEntity.java
  src/main/java/keeper/project/homepage/repository/posting/CategoryRepository.java
  src/main/java/keeper/project/homepage/service/posting/CategoryService.java
  src/main/java/keeper/project/homepage/user/controller/posting/CategoryController.java
  src/main/java/keeper/project/homepage/user/service/posting/CategoryService.java
  src/test/java/keeper/project/homepage/admin/controller/posting/AdminCategoryControllerTest.java
  src/test/java/keeper/project/homepage/user/controller/CategoryControllerTest.java
Labels: feat, docs, test

#169 Feature/출석부 오류 수정
  src/main/java/keeper/project/homepage/entity/attendance/AttendanceEntity.java
  src/main/java/keeper/project/homepage/repository/attendance/AttendanceRepository.java
  src/main/java/keeper/project/homepage/service/attendance/AttendanceService.java
Labels: fix

#168 Feature/썸네일 오류 수정
  src/main/java/keeper/project/homepage/admin/controller/library/BookManageController.java
  src/main/java/keeper/project/homepage/common/MultipartFileWrapper.java
  src/main/java/keeper/project/homepage/controller/posting/PostingController.java
  src/main/java/keeper/project/homepage/service/FileService.java
  src/main/java/keeper/project/homepage/service/ThumbnailService.java
  src/main/java/keeper/project/homepage/service/member/MemberService.java
  src/test/java/keeper/project/homepage/service/ThumbnailServiceTest.java
Labels: fix, refactor

#177 Feature/회원 조회 시 팔로우 체크
  src/main/java/keeper/project/homepage/controller/member/MemberController.java
  src/main/java/keeper/project/homepage/dto/result/OtherMemberInfoResult.java
  src/main/java/keeper/project/homepage/user/controller/member/MemberController.java
  src/main/java/keeper/project/homepage/user/service/member/MemberDeleteService.java
  src/main/java/keeper/project/homepage/user/service/member/MemberService.java
  src/test/java/keeper/project/homepage/service/member/MemberServiceTestSetup.java
Labels: feat

#176 Feature/게시판 랭킹 수정사항
  src/main/java/keeper/project/homepage/service/FileService.java
  src/main/java/keeper/project/homepage/service/ThumbnailService.java
  src/main/java/keeper/project/homepage/service/attendance/RankService.java
  src/test/java/keeper/project/homepage/controller/attendance/RankControllerTest.java
Labels: fix
