Repository KEEPER31337/Homepage-Back, pull requests merged in 2022-03, with the labels that each got.

#204 Feature/#191 댓글 admin user 분리
  src/main/java/keeper/project/homepage/admin/controller/posting/AdminCommentController.java
  src/main/java/keeper/project/homepage/admin/service/posting/AdminCommentService.java
  src/main/java/keeper/project/homepage/controller/posting/PostingController.java
  src/main/java/keeper/project/homepage/user/controller/posting/CommentController.java
  src/main/java/keeper/project/homepage/user/dto/posting/CommentDto.java
  src/main/java/keeper/project/homepage/user/service/posting/CommentService.java
  src/test/java/keeper/project/homepage/ApiControllerTestSetUp.java
  src/test/java/keeper/project/homepage/admin/controller/posting/AdminCommentControllerTest.java
  src/test/java/keeper/project/homepage/controller/posting/CommentControllerTest.java
  src/test/java/keeper/project/homepage/service/posting/CommentServiceTest.java
Labels: refactor

#207 Feature/#206_출석부_admin_user_분리
  src/main/java/keeper/project/homepage/user/controller/attendance/AttendanceController.java
  src/main/java/keeper/project/homepage/user/controller/attendance/GameController.java
  src/main/java/keeper/project/homepage/user/controller/attendance/RankController.java
  src/main/java/keeper/project/homepage/user/service/attendance/AttendanceService.java
  src/main/java/keeper/project/homepage/user/service/attendance/DateUtils.java
  src/main/java/keeper/project/homepage/user/service/attendance/GameService.java
  src/main/java/keeper/project/homepage/user/service/attendance/RankService.java
  src/test/java/keeper/project/homepage/ApiControllerTestSetUp.java
Labels: refactor

#214 refactor : 나머지 member service 이동
  src/main/java/keeper/project/homepage/common/service/sign/CustomMemberDetailService.java
  src/main/java/keeper/project/homepage/user/service/member/MemberHasCommentDislikeService.java
  src/main/java/keeper/project/homepage/user/service/member/MemberHasCommentLikeService.java
  src/main/java/keeper/project/homepage/user/service/posting/CommentService.java
  src/test/java/keeper/project/homepage/ApiControllerTestSetUp.java
  src/test/java/keeper/project/homepage/service/member/MemberHasCommentDislikeServiceTest.java
  src/test/java/keeper/project/homepage/service/member/MemberHasCommentLikeServiceTest.java
Labels: refactor

#182 fix : 도서관 오류 수정
  src/main/java/keeper/project/homepage/admin/service/library/BookManageService.java
  src/main/java/keeper/project/homepage/entity/library/BookEntity.java
Labels: fix

#223 Feature/#221 게시판 response dto
  src/main/java/keeper/project/homepage/entity/posting/PostingEntity.java
  src/main/java/keeper/project/homepage/user/controller/posting/PostingController.java
  src/main/java/keeper/project/homepage/user/dto/posting/PostingBestDto.java
  src/main/java/keeper/project/homepage/user/dto/posting/PostingResponseDto.java
  src/main/java/keeper/project/homepage/user/service/posting/PostingService.java
  src/test/java/keeper/project/homepage/controller/posting/PostingControllerTest.java
Labels: fix, refactor

#224 Feature/#216 직위로 멤버 정보 받아오기
  build.gradle
  src/main/generated/keeper/project/homepage/common/mapper/CommonMemberMapperImpl.java
  src/main/java/keeper/project/homepage/common/controller/member/CommonMemberController.java
  src/main/java/keeper/project/homepage/common/dto/member/CommonMemberDto.java
  src/main/java/keeper/project/homepage/common/mapper/CommonMemberMapper.java
  src/main/java/keeper/project/homepage/common/service/member/CommonMemberService.java
  src/main/java/keeper/project/homepage/entity/member/MemberEntity.java
  src/test/java/keeper/project/homepage/common/controller/MemberControllerTest.java
Labels: feat

#222 Feature/#192 썸네일이 포함된 response dto 수정
  src/main/java/keeper/project/homepage/admin/dto/etc/StaticWriteSubtitleImageResult.java
  src/main/java/keeper/project/homepage/admin/dto/member/MemberDto.java
  src/main/java/keeper/project/homepage/common/controller/util/ImageController.java
  src/main/java/keeper/project/homepage/user/dto/attendance/RankDto.java
  src/main/java/keeper/project/homepage/user/dto/library/BookResult.java
  src/main/java/keeper/project/homepage/user/dto/member/MemberDto.java
  src/main/java/keeper/project/homepage/user/dto/member/OtherMemberInfoResult.java
  src/main/java/keeper/project/homepage/user/dto/posting/CommentDto.java
  src/main/java/keeper/project/homepage/user/dto/posting/PostingBestDto.java
  src/test/java/keeper/project/homepage/ApiControllerTestHelper.java
  src/test/java/keeper/project/homepage/admin/controller/about/AdminAboutSubtitleControllerTest.java
  src/test/java/keeper/project/homepage/controller/attendance/RankControllerTest.java
  src/test/java/keeper/project/homepage/controller/library/LibraryMainControllerTest.java
  src/test/java/keeper/project/homepage/controller/posting/CommentControllerTest.java
  src/test/java/keeper/project/homepage/controller/posting/PostingControllerTest.java
Labels: fix, docs

#231 Feature/#218 팔로워 팔로잉 숫자 조회 기능 추가
  src/docs/asciidoc/member_info.adoc
  src/main/java/keeper/project/homepage/user/controller/member/MemberController.java
  src/main/java/keeper/project/homepage/user/dto/member/MemberFollowDto.java
  src/main/java/keeper/project/homepage/user/service/member/MemberService.java
  src/test/java/keeper/project/homepage/ApiControllerTestHelper.java
  src/test/java/keeper/project/homepage/controller/member/MemberControllerTest.java
Labels: feat, docs, test

#232 Feature/#196_게시판_비밀글_로직_수정
  src/main/java/keeper/project/homepage/user/controller/posting/PostingController.java
Labels: fix

#233 feat : 최신 공지글 목록 기능 추가
  src/main/java/keeper/project/homepage/repository/posting/PostingRepository.java
  src/main/java/keeper/project/homepage/user/controller/posting/PostingController.java
  src/main/java/keeper/project/homepage/user/service/posting/PostingService.java
  src/test/java/keeper/project/homepage/controller/posting/PostingControllerTest.java
Labels: feat

#234 Feature/#218 다른 회원 게시글 조회 기능 추가
  src/docs/asciidoc/member_posting.adoc
  src/main/java/keeper/project/homepage/repository/posting/PostingRepository.java
  src/main/java/keeper/project/homepage/user/controller/member/MemberController.java
  src/main/java/keeper/project/homepage/user/service/member/MemberService.java
  src/main/java/keeper/project/homepage/user/service/posting/PostingService.java
  src/test/java/keeper/project/homepage/ApiControllerTestHelper.java
  src/test/java/keeper/project/homepage/ApiControllerTestSetUp.java
  src/test/java/keeper/project/homepage/controller/member/MemberControllerFindPostingTest.java
Labels: feat, docs, test

#235 Feature/#226 포인트 선물기록 오류수정
  src/docs/asciidoc/pointLog.adoc
  src/main/java/keeper/project/homepage/entity/point/PointLogEntity.java
  src/main/java/keeper/project/homepage/exception/CustomTransferPointLackException.java
  src/main/java/keeper/project/homepage/exception/ExceptionAdvice.java
  src/main/java/keeper/project/homepage/exception/point/CustomPointLackException.java
  src/main/java/keeper/project/homepage/exception/point/CustomPointLogRequestNullException.java
  src/main/java/keeper/project/homepage/repository/point/PointLogRepository.java
  src/main/java/keeper/project/homepage/user/controller/point/PointLogController.java
  src/main/java/keeper/project/homepage/user/dto/point/request/PointGiftLogRequestDto.java
  src/main/java/keeper/project/homepage/user/dto/point/request/PointLogRequestDto.java
  src/main/java/keeper/project/homepage/user/dto/point/result/PointGiftLogResultDto.java
  src/main/java/keeper/project/homepage/user/dto/point/result/PointLogResultDto.java
  src/main/java/keeper/project/homepage/user/service/attendance/AttendanceService.java
  src/main/java/keeper/project/homepage/user/service/attendance/GameService.java
  src/main/java/keeper/project/homepage/user/service/point/PointLogService.java
  src/main/resources/exception.properties
  src/test/java/keeper/project/homepage/ApiControllerTestHelper.java
  src/test/java/keeper/project/homepage/service/member/MemberServiceTestSetup.java
  src/test/java/keeper/project/homepage/service/point/PointLogServiceTest.java
  src/test/java/keeper/project/homepage/user/controller/point/PointLogControllerTest.java
Labels: fix, refactor, docs, test

#238 Feature/회원 게시글 조회 긴급 이슈 수정
  src/main/java/keeper/project/homepage/user/controller/member/MemberController.java
  src/main/java/keeper/project/homepage/user/service/member/MemberService.java
Labels: fix

#247 Feature/#229 스터디 api 제작
  src/docs/asciidoc/keeper.adoc
  src/docs/asciidoc/study/study.adoc
  src/main/generated/keeper/project/homepage/user/mapper/StudyMapperImpl.java
  src/main/java/keeper/project/homepage/entity/member/MemberEntity.java
  src/main/java/keeper/project/homepage/entity/study/StudyEntity.java
  src/main/java/keeper/project/homepage/entity/study/StudyHasMemberEntity.java
  src/main/java/keeper/project/homepage/entity/study/StudyHasMemberEntityPK.java
  src/main/java/keeper/project/homepage/exception/ExceptionAdvice.java
  src/main/java/keeper/project/homepage/exception/study/CustomIpAddressNotFoundException.java
  src/main/java/keeper/project/homepage/exception/study/CustomSeasonInvalidException.java
  src/main/java/keeper/project/homepage/exception/study/CustomStudyIsNotMineException.java
  src/main/java/keeper/project/homepage/exception/study/CustomStudyNotFoundException.java
  src/main/java/keeper/project/homepage/repository/study/StudyHasMemberRepository.java
  src/main/java/keeper/project/homepage/repository/study/StudyRepository.java
  src/main/java/keeper/project/homepage/user/controller/study/StudyController.java
  src/main/java/keeper/project/homepage/user/dto/study/CreateStudyRequestDto.java
  src/main/java/keeper/project/homepage/user/dto/study/ModifyStudyRequestDto.java
  src/main/java/keeper/project/homepage/user/dto/study/StudyDto.java
  src/main/java/keeper/project/homepage/user/dto/study/StudyMemberRequestDto.java
  src/main/java/keeper/project/homepage/user/dto/study/StudyRequestDto.java
  src/main/java/keeper/project/homepage/user/dto/study/StudyYearSeasonDto.java
  src/main/java/keeper/project/homepage/user/mapper/StudyMapper.java
  src/main/java/keeper/project/homepage/user/service/study/StudyService.java
  src/main/java/keeper/project/homepage/util/service/ThumbnailService.java
  src/main/resources/exception.properties
  src/main/resources/exception_en.properties
  src/main/resources/exception_ko.properties
  src/test/java/keeper/project/homepage/ApiControllerTestSetUp.java
  src/test/java/keeper/project/homepage/user/controller/study/StudyControllerTest.java
  src/test/java/keeper/project/homepage/user/controller/study/StudyControllerTestSetup.java
Labels: feat, fix, docs, test

#241 fix: 팔로우 시 상대 프로필 불러오기 안되던 버그 해결
  src/main/java/keeper/project/homepage/user/service/member/MemberService.java
Labels: fix

#244 Feature/#240 페이지블럭 서브타이틀 버그
  src/main/java/keeper/project/homepage/admin/dto/etc/StaticWriteSubtitleImageResult.java
  src/test/java/keeper/project/homepage/user/controller/about/AboutTitleControllerTest.java
Labels: fix, test

#239 Feature/#187 회원정보조회수정
  src/docs/asciidoc/member_info.adoc
  src/docs/asciidoc/member_infoAdmin.adoc
  src/main/java/keeper/project/homepage/admin/controller/member/AdminMemberController.java
  src/main/java/keeper/project/homepage/admin/dto/member/MemberDto.java
  src/main/java/keeper/project/homepage/admin/service/member/AdminMemberService.java
  src/main/java/keeper/project/homepage/user/controller/member/MemberController.java
  src/main/java/keeper/project/homepage/user/dto/member/MemberDto.java
  src/main/java/keeper/project/homepage/user/dto/member/OtherMemberInfoResult.java
  src/main/java/keeper/project/homepage/user/service/member/MemberService.java
  src/test/java/keeper/project/homepage/ApiControllerTestHelper.java
  src/test/java/keeper/project/homepage/admin/controller/member/AdminMemberControllerTest.java
  src/test/java/keeper/project/homepage/controller/member/MemberControllerFindPostingTest.java
  src/test/java/keeper/project/homepage/controller/member/MemberControllerTest.java
  src/test/java/keeper/project/homepage/controller/member/MemberUpdateControllerTest.java
  src/test/java/keeper/project/homepage/user/controller/member/MemberControllerTest.java
Labels: fix, docs, test

#245 Feature/#242 썸네일 response에 ip port 포함
  src/main/java/keeper/project/homepage/admin/dto/etc/StaticWriteSubtitleImageResult.java
  src/main/java/keeper/project/homepage/entity/member/MemberEntity.java
  src/main/java/keeper/project/homepage/user/controller/member/MemberController.java
  src/main/java/keeper/project/homepage/user/dto/attendance/RankDto.java
  src/main/java/keeper/project/homepage/user/dto/library/BookResult.java
  src/main/java/keeper/project/homepage/user/dto/member/MemberDto.java
  src/main/java/keeper/project/homepage/user/dto/member/OtherMemberInfoResult.java
  src/main/java/keeper/project/homepage/user/dto/posting/CommentDto.java
  src/main/java/keeper/project/homepage/user/dto/posting/PostingBestDto.java
  src/main/java/keeper/project/homepage/user/dto/posting/PostingResponseDto.java
  src/main/java/keeper/project/homepage/user/service/member/MemberService.java
  src/main/java/keeper/project/homepage/util/EnvironmentProperty.java
Labels: feat, fix

#249 fix : 팔로우 확인 오류 수정
  src/main/java/keeper/project/homepage/user/service/member/MemberService.java
  src/test/java/keeper/project/homepage/controller/member/MemberControllerFindPostingTest.java
Labels: fix
