Repository KEEPER31337/Homepage-Back, pull requests merged in 2022-05, with the labels that each got.

#275 #200 jwt 최적화
  src/main/java/keeper/project/homepage/common/service/sign/CustomMemberDetailService.java
  src/main/java/keeper/project/homepage/common/service/sign/SignInService.java
  src/main/java/keeper/project/homepage/common/service/util/AuthService.java
  src/main/java/keeper/project/homepage/config/security/JwtAuthenticationFilter.java
  src/main/java/keeper/project/homepage/config/security/JwtMemberEntity.java
  src/main/java/keeper/project/homepage/config/security/JwtTokenProvider.java
  src/main/java/keeper/project/homepage/entity/member/MemberEntity.java
  src/test/java/keeper/project/homepage/controller/util/AuthControllerTest.java
Labels: fix

#274 Feature/게시판 파일 삭제 로직 수정
  src/docs/asciidoc/posting.adoc
  src/main/java/keeper/project/homepage/user/controller/posting/PostingController.java
  src/main/java/keeper/project/homepage/util/service/FileService.java
  src/test/java/keeper/project/homepage/controller/posting/PostingControllerTest.java
Labels: fix

#267 Feature/#195 게시판 예외 메세지 구현
  src/main/java/keeper/project/homepage/exception/ExceptionAdvice.java
  src/main/java/keeper/project/homepage/exception/posting/CustomPostingAccessDeniedException.java
  src/main/java/keeper/project/homepage/exception/posting/CustomPostingIncorrectException.java
  src/main/java/keeper/project/homepage/exception/posting/CustomPostingNotFoundException.java
  src/main/java/keeper/project/homepage/exception/posting/CustomPostingTempException.java
  src/main/java/keeper/project/homepage/user/controller/member/MemberController.java
  src/main/java/keeper/project/homepage/user/controller/posting/PostingController.java
  src/main/java/keeper/project/homepage/user/dto/posting/PostingResponseDto.java
  src/main/java/keeper/project/homepage/user/service/member/MemberService.java
  src/main/java/keeper/project/homepage/user/service/posting/PostingService.java
  src/main/resources/exception.properties
  src/test/java/keeper/project/homepage/controller/member/MemberControllerFindPostingTest.java
Labels: feat, refactor

#272 Feature/#266 member api 요청
  src/docs/asciidoc/member_info.adoc
  src/main/java/keeper/project/homepage/entity/member/MemberEntity.java
  src/main/java/keeper/project/homepage/user/controller/member/MemberController.java
  src/main/java/keeper/project/homepage/user/dto/member/MultiMemberResponseDto.java
  src/main/java/keeper/project/homepage/user/service/member/MemberService.java
  src/test/java/keeper/project/homepage/user/controller/member/MemberControllerTest.java
Labels: feat, docs, test

#276 refactor : 게시판 테스트 코드 리팩토링
  src/test/java/keeper/project/homepage/ApiControllerTestHelper.java
  src/test/java/keeper/project/homepage/admin/controller/about/AdminAboutContentControllerTest.java
  src/test/java/keeper/project/homepage/admin/controller/about/AdminAboutTitleControllerTest.java
  src/test/java/keeper/project/homepage/admin/service/about/AdminAboutTitleServiceTest.java
  src/test/java/keeper/project/homepage/controller/posting/PostingControllerTest.java
  src/test/java/keeper/project/homepage/user/controller/about/AboutTitleControllerTest.java
  src/test/java/keeper/project/homepage/user/controller/study/StudyControllerTestSetup.java
Labels: refactor

#278 Feature/253 study 리팩토링&버그수정
  .github/workflows/keeper_homepage_back.yml
  src/main/generated/keeper/project/homepage/common/mapper/CommonMemberMapperImpl.java
  src/main/generated/keeper/project/homepage/user/mapper/StudyMapperImpl.java
  src/main/java/keeper/project/homepage/user/service/study/StudyService.java
  src/test/java/keeper/project/homepage/user/controller/study/StudyControllerTest.java
Labels: fix

#279 Feature/273 비밀번호 필터링 제거
  src/main/java/keeper/project/homepage/common/controller/sign/SignUpController.java
  src/main/java/keeper/project/homepage/common/service/sign/DuplicateCheckService.java
  src/main/java/keeper/project/homepage/common/service/sign/SignUpService.java
  src/main/java/keeper/project/homepage/user/service/member/MemberService.java
Labels: feat, fix, refactor

#289 Feature/287 ctf 개발준비
  src/main/java/keeper/project/homepage/entity/ctf/CtfChallengeCategoryEntity.java
  src/main/java/keeper/project/homepage/entity/ctf/CtfChallengeEntity.java
  src/main/java/keeper/project/homepage/entity/ctf/CtfChallengeTypeEntity.java
  src/main/java/keeper/project/homepage/entity/ctf/CtfContestEntity.java
  src/main/java/keeper/project/homepage/entity/ctf/CtfFlagEntity.java
  src/main/java/keeper/project/homepage/entity/ctf/CtfSubmitLogEntity.java
  src/main/java/keeper/project/homepage/entity/ctf/CtfTeamEntity.java
  src/main/java/keeper/project/homepage/repository/ctf/CtfChallengeCategoryRepository.java
  src/main/java/keeper/project/homepage/repository/ctf/CtfChallengeRepository.java
  src/main/java/keeper/project/homepage/repository/ctf/CtfChallengeTypeRepository.java
  src/main/java/keeper/project/homepage/repository/ctf/CtfContestRepository.java
  src/main/java/keeper/project/homepage/repository/ctf/CtfFlagRepository.java
  src/main/java/keeper/project/homepage/repository/ctf/CtfSubmitLogRepository.java
  src/main/java/keeper/project/homepage/repository/ctf/CtfTeamRepository.java
  src/test/java/keeper/project/homepage/repository/ctf/CtfChallengeCategoryRepositoryTest.java
  src/test/java/keeper/project/homepage/repository/ctf/CtfChallengeRepositoryTest.java
  src/test/java/keeper/project/homepage/repository/ctf/CtfChallengeTypeRepositoryTest.java
  src/test/java/keeper/project/homepage/repository/ctf/CtfContestRepositoryTest.java
  src/test/java/keeper/project/homepage/repository/ctf/CtfFlagRepositoryTest.java
  src/test/java/keeper/project/homepage/repository/ctf/CtfSubmitLogRepositoryTest.java
  src/test/java/keeper/project/homepage/repository/ctf/CtfTeamRepositoryTest.java
  src/test/java/keeper/project/homepage/repository/ctf/CtfTestHelper.java
Labels: feat, test

#290 Feature/284 ctf 출제자 api
  src/docs/asciidoc/admin.adoc
  src/docs/asciidoc/ctf/ctfAdmin.adoc
  src/main/java/keeper/project/homepage/admin/controller/ctf/CtfAdminController.java
  src/main/java/keeper/project/homepage/admin/dto/ctf/CtfChallengeAdminDto.java
  src/main/java/keeper/project/homepage/admin/dto/ctf/CtfContestDto.java
  src/main/java/keeper/project/homepage/admin/dto/ctf/CtfProbMakerDto.java
  src/main/java/keeper/project/homepage/admin/dto/ctf/CtfSubmitLogDto.java
  src/main/java/keeper/project/homepage/admin/service/ctf/CtfAdminService.java
  src/main/java/keeper/project/homepage/common/dto/member/CommonMemberDto.java
  src/main/java/keeper/project/homepage/common/dto/result/PageResult.java
  src/main/java/keeper/project/homepage/common/service/ResponseService.java
  src/main/java/keeper/project/homepage/entity/ctf/CtfChallengeCategoryEntity.java
  src/main/java/keeper/project/homepage/entity/ctf/CtfChallengeEntity.java
  src/main/java/keeper/project/homepage/entity/ctf/CtfChallengeTypeEntity.java
  src/main/java/keeper/project/homepage/entity/ctf/CtfContestEntity.java
  src/main/java/keeper/project/homepage/entity/ctf/CtfDynamicChallengeInfoEntity.java
  src/main/java/keeper/project/homepage/entity/ctf/CtfFlagEntity.java
  src/main/java/keeper/project/homepage/entity/ctf/CtfSubmitLogEntity.java
  src/main/java/keeper/project/homepage/entity/ctf/CtfTeamEntity.java
  src/main/java/keeper/project/homepage/exception/ExceptionAdvice.java
  src/main/java/keeper/project/homepage/exception/ctf/CustomContestNotFoundException.java
  src/main/java/keeper/project/homepage/exception/ctf/CustomCtfCategoryNotFoundException.java
  src/main/java/keeper/project/homepage/exception/ctf/CustomCtfChallengeNotFoundException.java
  src/main/java/keeper/project/homepage/exception/ctf/CustomCtfTypeNotFoundException.java
  src/main/java/keeper/project/homepage/repository/ctf/CtfChallengeRepository.java
  src/main/java/keeper/project/homepage/repository/ctf/CtfContestRepository.java
  src/main/java/keeper/project/homepage/repository/ctf/CtfDynamicChallengeInfoRepository.java
  src/main/java/keeper/project/homepage/repository/ctf/CtfSubmitLogRepository.java
  src/main/java/keeper/project/homepage/user/controller/member/MemberController.java
  src/main/java/keeper/project/homepage/user/dto/ctf/CtfChallengeCategoryDto.java
  src/main/java/keeper/project/homepage/user/dto/ctf/CtfChallengeDto.java
  src/main/java/keeper/project/homepage/user/dto/ctf/CtfChallengeTypeDto.java
  src/main/java/keeper/project/homepage/user/dto/ctf/CtfDynamicChallengeInfoDto.java
  src/main/java/keeper/project/homepage/user/dto/ctf/CtfTeamDto.java
  src/main/java/keeper/project/homepage/util/dto/FileDto.java
  src/main/java/keeper/project/homepage/util/service/FileService.java
  src/main/resources/exception.properties
  src/test/java/keeper/project/homepage/ApiControllerTestHelper.java
  src/test/java/keeper/project/homepage/admin/controller/about/AdminAboutTitleControllerTest.java
  src/test/java/keeper/project/homepage/admin/controller/ctf/CtfAdminControllerTest.java
  src/test/java/keeper/project/homepage/admin/controller/member/AdminMemberControllerTest.java
  src/test/java/keeper/project/homepage/controller/ctf/CtfControllerTestHelper.java
  src/test/java/keeper/project/homepage/repository/ctf/CtfChallengeRepositoryTest.java
  src/test/java/keeper/project/homepage/repository/ctf/CtfTestHelper.java
  src/test/java/keeper/project/homepage/user/controller/member/MemberControllerTest.java
Labels: feat, docs, test

#288 Feature/#271 이미지 로딩 개선
  src/main/java/keeper/project/homepage/admin/controller/library/BookManageController.java
  src/main/java/keeper/project/homepage/admin/service/about/AdminAboutSubtitleService.java
  src/main/java/keeper/project/homepage/common/controller/util/ImageController.java
  src/main/java/keeper/project/homepage/user/controller/posting/PostingController.java
  src/main/java/keeper/project/homepage/user/service/member/MemberService.java
  src/main/java/keeper/project/homepage/user/service/study/StudyService.java
  src/main/java/keeper/project/homepage/util/ImageCenterCropping.java
  src/main/java/keeper/project/homepage/util/ImageResize.java
  src/main/java/keeper/project/homepage/util/ImageResizing.java
  src/main/java/keeper/project/homepage/util/service/FileService.java
  src/main/java/keeper/project/homepage/util/service/ThumbnailService.java
  src/test/java/keeper/project/homepage/service/ThumbnailServiceTest.java
Labels: fix

#295 fix: 스터디 수정 API 수정
  src/main/java/keeper/project/homepage/repository/study/StudyHasMemberRepository.java
  src/main/java/keeper/project/homepage/user/controller/study/StudyController.java
  src/main/java/keeper/project/homepage/user/dto/study/ModifyStudyRequestDto.java
  src/main/java/keeper/project/homepage/user/service/study/StudyService.java
  src/test/java/keeper/project/homepage/user/controller/study/StudyControllerTest.java
Labels: fix

#293 Feature/#285_IP_가져오기_방식_수정
  src/main/java/keeper/project/homepage/user/controller/attendance/AttendanceController.java
  src/main/java/keeper/project/homepage/user/controller/posting/CommentController.java
  src/main/java/keeper/project/homepage/user/controller/posting/PostingController.java
  src/main/java/keeper/project/homepage/user/dto/posting/CommentDto.java
  src/main/java/keeper/project/homepage/util/ClientUtil.java
  src/test/java/keeper/project/homepage/controller/attendance/AttendanceControllerTest.java
  src/test/java/keeper/project/homepage/controller/posting/CommentControllerTest.java
  src/test/java/keeper/project/homepage/controller/posting/PostingControllerTest.java
Labels: fix

#299 Feature/#298 출석 랭킹 api 수정
  src/docs/asciidoc/rank.adoc
  src/main/java/keeper/project/homepage/user/controller/attendance/RankController.java
  src/main/java/keeper/project/homepage/user/dto/attendance/RankDto.java
  src/main/java/keeper/project/homepage/user/service/attendance/RankService.java
  src/test/java/keeper/project/homepage/controller/attendance/RankControllerTest.java
Labels: fix, test

#304 Feature/#298 출석 랭킹 API 오류 수정
  src/main/java/keeper/project/homepage/user/service/attendance/RankService.java
Labels: fix
