Repository KEEPER31337/Homepage-Back, pull requests merged in 2022-01, with the labels that each got.

#18 Feature/구db 패스워드 동기화
  src/main/java/keeper/project/homepage/controller/sign/SignInController.java
  src/main/java/keeper/project/homepage/service/CustomPasswordService.java
  src/test/java/keeper/project/homepage/service/CustomPasswordServiceTest.java
Labels: feat

#21 Feature/api 문서 배포
  docker/application.properties
  docker/docker-compose.yml
  docker/readme.md
  docker/run.sh
  gradlew
Labels: feat

#22 Feature/게시판 crud
  src/docs/asciidoc/comment.adoc
  src/docs/asciidoc/keeper.adoc
  src/docs/asciidoc/posting.adoc
  src/main/java/keeper/project/homepage/controller/CommentController.java
  src/main/java/keeper/project/homepage/controller/PostingController.java
  src/main/java/keeper/project/homepage/dto/CommentDto.java
  src/main/java/keeper/project/homepage/dto/FileDto.java
  src/main/java/keeper/project/homepage/dto/PostingDto.java
  src/main/java/keeper/project/homepage/entity/CategoryEntity.java
  src/main/java/keeper/project/homepage/entity/CommentEntity.java
  src/main/java/keeper/project/homepage/entity/FileEntity.java
  src/main/java/keeper/project/homepage/entity/MemberHasPostingDislikeEntity.java
  src/main/java/keeper/project/homepage/entity/MemberHasPostingLikeEntity.java
  src/main/java/keeper/project/homepage/entity/MemberPostingEntityPK.java
  src/main/java/keeper/project/homepage/entity/PostingEntity.java
  src/main/java/keeper/project/homepage/exception/CustomCommentNotFoundException.java
  src/main/java/keeper/project/homepage/repository/CategoryRepository.java
  src/main/java/keeper/project/homepage/repository/CommentRepository.java
  src/main/java/keeper/project/homepage/repository/FileRepository.java
  src/main/java/keeper/project/homepage/repository/MemberHasPostingDislikeRepository.java
  src/main/java/keeper/project/homepage/repository/MemberHasPostingLikeRepository.java
  src/main/java/keeper/project/homepage/repository/PostingRepository.java
  src/main/java/keeper/project/homepage/service/CommentService.java
  src/main/java/keeper/project/homepage/service/FileService.java
  src/main/java/keeper/project/homepage/service/PostingService.java
  src/test/java/keeper/project/homepage/controller/CommentControllerTest.java
  src/test/java/keeper/project/homepage/controller/PostingControllerTest.java
  src/test/java/keeper/project/homepage/repository/CommentRepositoryTest.java
  src/test/java/keeper/project/homepage/service/CommentServiceTest.java
  src/test/resources/org/springframework/restdocs/templates/request-parts.snippet
Labels: feat

#49 feat : 도서관 폴더 생성
  src/main/java/keeper/project/homepage/controller/library/BookController.java
  src/main/java/keeper/project/homepage/entity/library/BookEntity.java
  src/main/java/keeper/project/homepage/repository/library/BookRepository.java
  src/main/java/keeper/project/homepage/service/library/BookManageService.java
  src/test/java/keeper/project/homepage/ApiControllerTestSetUp.java
  src/test/java/keeper/project/homepage/controller/BookControllerTest.java
Labels: feat

#67 Feature/파일 다운로드
  src/docs/asciidoc/posting.adoc
  src/main/java/keeper/project/homepage/controller/posting/PostingController.java
  src/main/java/keeper/project/homepage/dto/posting/PostingDto.java
  src/main/java/keeper/project/homepage/entity/posting/PostingEntity.java
  src/test/java/keeper/project/homepage/controller/posting/PostingControllerTest.java
Labels: feat

#76 Feature/이미지 불러오기
  build.gradle
  src/docs/asciidoc/keeper.adoc
  src/docs/asciidoc/util.adoc
  src/main/java/keeper/project/homepage/controller/util/ImageController.java
  src/main/java/keeper/project/homepage/dto/FileDto.java
  src/main/java/keeper/project/homepage/exception/CustomFileNotFoundException.java
  src/main/java/keeper/project/homepage/exception/ExceptionAdvice.java
  src/main/java/keeper/project/homepage/service/FileService.java
  src/main/java/keeper/project/homepage/service/ThumbnailService.java
  src/main/resources/exception.properties
  src/main/resources/exception_en.properties
  src/main/resources/exception_ko.properties
  src/test/java/keeper/project/homepage/controller/util/ImageControllerTest.java
Labels: feat

#77 Feature/게시판 비밀글 기능
  src/main/java/keeper/project/homepage/controller/posting/PostingController.java
  src/main/java/keeper/project/homepage/entity/posting/PostingEntity.java
  src/main/java/keeper/project/homepage/service/posting/PostingService.java
  src/test/java/keeper/project/homepage/controller/posting/PostingControllerTest.java
Labels: feat

#78 Feature/게시판 검색 기능 수정
  src/main/java/keeper/project/homepage/repository/member/MemberRepository.java
  src/main/java/keeper/project/homepage/repository/posting/PostingRepository.java
  src/main/java/keeper/project/homepage/service/posting/PostingService.java
Labels: feat

#86 Feature/댓글 기능 수정
  src/docs/asciidoc/comment.adoc
  src/main/java/keeper/project/homepage/controller/member/MemberController.java
  src/main/java/keeper/project/homepage/controller/posting/CommentController.java
  src/main/java/keeper/project/homepage/controller/sign/SignInController.java
  src/main/java/keeper/project/homepage/controller/sign/SignUpController.java
  src/main/java/keeper/project/homepage/dto/posting/CommentDto.java
  src/main/java/keeper/project/homepage/service/ResponseService.java
  src/main/java/keeper/project/homepage/service/posting/CommentService.java
  src/test/java/keeper/project/homepage/controller/posting/CommentControllerTest.java
  src/test/java/keeper/project/homepage/service/posting/CommentServiceTest.java
Labels: style, refactor, test

#87 fix : 권한 Jobs로 통일
  src/docs/asciidoc/util.adoc
  src/main/java/keeper/project/homepage/controller/member/MemberController.java
  src/main/java/keeper/project/homepage/controller/util/AuthController.java
  src/main/java/keeper/project/homepage/dto/member/MemberDto.java
  src/main/java/keeper/project/homepage/entity/member/MemberEntity.java
  src/main/java/keeper/project/homepage/entity/member/MemberHasMemberJobEntity.java
  src/main/java/keeper/project/homepage/entity/member/MemberHasMemberJobPK.java
  src/main/java/keeper/project/homepage/repository/member/MemberHasMemberJobRepository.java
  src/main/java/keeper/project/homepage/repository/member/MemberJobRepository.java
  src/main/java/keeper/project/homepage/service/member/CustomMemberDetailService.java
  src/main/java/keeper/project/homepage/service/sign/SignInService.java
  src/main/java/keeper/project/homepage/service/sign/SignUpService.java
  src/main/java/keeper/project/homepage/service/util/AuthService.java
  src/test/java/keeper/project/homepage/ApiControllerTestSetUp.java
  src/test/java/keeper/project/homepage/controller/member/MemberControllerTest.java
  src/test/java/keeper/project/homepage/controller/posting/CommentControllerTest.java
  src/test/java/keeper/project/homepage/controller/posting/PostingControllerTest.java
  src/test/java/keeper/project/homepage/controller/sign/SignInControllerTest.java
  src/test/java/keeper/project/homepage/controller/sign/SignUpControllerTest.java
  src/test/java/keeper/project/homepage/controller/util/AuthControllerTest.java
  src/test/java/keeper/project/homepage/repository/member/MemberHasCommentDislikeRepositoryTest.java
  src/test/java/keeper/project/homepage/repository/member/MemberHasCommentLikeRepositoryTest.java
  src/test/java/keeper/project/homepage/repository/member/MemberRepositoryTest.java
  src/test/java/keeper/project/homepage/repository/posting/CommentRepositoryTest.java
  src/test/java/keeper/project/homepage/service/ThumbnailServiceTest.java
  src/test/java/keeper/project/homepage/service/mail/MailServiceTest.java
  src/test/java/keeper/project/homepage/service/member/MemberHasCommentDislikeServiceTest.java
  src/test/java/keeper/project/homepage/service/member/MemberHasCommentLikeServiceTest.java
  src/test/java/keeper/project/homepage/service/member/MemberServiceTest.java
  src/test/java/keeper/project/homepage/service/posting/CommentServiceTest.java
Labels: fix

#50 feat : 아이디찾기, 비밀번호 찾기 Test Code, API 문서 제작
  src/docs/asciidoc/signin.adoc
  src/test/java/keeper/project/homepage/controller/member/MemberControllerTest.java
  src/test/java/keeper/project/homepage/controller/posting/PostingControllerTest.java
  src/test/java/keeper/project/homepage/controller/sign/SignInControllerTest.java
  src/test/java/keeper/project/homepage/repository/member/MemberRepositoryTest.java
Labels: feat

#88 Feature/도서 대여 기능
  src/docs/asciidoc/bookmanage.adoc
  src/main/java/keeper/project/homepage/controller/library/BookManageController.java
  src/main/java/keeper/project/homepage/dto/BookBorrowDto.java
  src/main/java/keeper/project/homepage/entity/library/BookBorrowEntity.java
  src/main/java/keeper/project/homepage/repository/library/BookBorrowRepository.java
  src/main/java/keeper/project/homepage/service/library/BookManageService.java
  src/test/java/keeper/project/homepage/controller/library/BookManageControllerTest.java
Labels: feat
