Repository KEEPER31337/Homepage-Back, pull requests merged in 2023-01, with the labels that each got.

#473 CTF 상속 대신 컴포지션 사용하기 #332
  src/main/java/keeper/project/homepage/ctf/dto/CtfChallengeAdminDto.java
  src/main/java/keeper/project/homepage/ctf/dto/CtfChallengeDto.java
  src/main/java/keeper/project/homepage/ctf/dto/CtfCommonChallengeDto.java
  src/main/java/keeper/project/homepage/ctf/service/CtfAdminService.java
  src/test/java/keeper/project/homepage/ctf/controller/CtfAdminControllerTest.java
  src/test/java/keeper/project/homepage/ctf/controller/CtfSpringTestHelper.java
  src/test/java/keeper/project/homepage/ctf/service/CtfAdminServiceTest.java
  src/test/java/keeper/project/homepage/ctf/service/CtfServiceTest.java
  src/test/java/keeper/project/homepage/ctf/service/CtfTeamServiceTest.java
Labels: ❤️ refactor

#477 Refactor: dto 이동
  src/main/java/keeper/project/homepage/attendance/dto/AttendanceDto.java
  src/main/java/keeper/project/homepage/attendance/dto/AttendancePointDto.java
  src/main/java/keeper/project/homepage/attendance/dto/AttendanceResultDto.java
  src/main/java/keeper/project/homepage/attendance/dto/GameInfoDto.java
  src/main/java/keeper/project/homepage/attendance/dto/LottoDto.java
  src/main/java/keeper/project/homepage/attendance/dto/RankDto.java
  src/main/java/keeper/project/homepage/attendance/dto/RouletteDto.java
Labels: ❤️ refactor, 👀 good first issue

#479 fix: DB의 저장 범위와 LocalDateTime 자료형의 저장 범위가 달라 String이 일치하지 않았던 문제 해결
  src/main/java/keeper/project/homepage/ctf/dto/CtfCommonChallengeDto.java
  src/test/java/keeper/project/homepage/ctf/controller/CtfChallengeControllerTest.java
Labels: 🛠 bug, ✏️ test

#483 Feature/#366 admin seminar service 실패테스트구현
  src/main/java/keeper/project/homepage/clerk/service/AdminSeminarService.java
  src/test/java/keeper/project/homepage/clerk/service/AdminSeminarServiceTest.java
Labels: ✏️ test

#484 Feature/#331 Member 관련 코드를 리팩토링 한다.
  src/main/java/keeper/project/homepage/clerk/service/AdminSeminarService.java
  src/main/java/keeper/project/homepage/clerk/service/SurveyService.java
  src/main/java/keeper/project/homepage/member/controller/AdminMemberController.java
  src/main/java/keeper/project/homepage/member/controller/MemberController.java
  src/main/java/keeper/project/homepage/member/dto/MultiMemberResponseDto.java
  src/main/java/keeper/project/homepage/member/dto/OtherMemberInfoResult.java
  src/main/java/keeper/project/homepage/member/dto/request/MemberDemeritRequestDto.java
  src/main/java/keeper/project/homepage/member/dto/request/MemberGenerationRequestDto.java
  src/main/java/keeper/project/homepage/member/dto/request/MemberJobRequestDto.java
  src/main/java/keeper/project/homepage/member/dto/request/MemberMeritRequestDto.java
  src/main/java/keeper/project/homepage/member/dto/request/MemberRankRequestDto.java
  src/main/java/keeper/project/homepage/member/dto/request/MemberTypeRequestDto.java
  src/main/java/keeper/project/homepage/member/dto/response/MemberFollowResponseDto.java
  src/main/java/keeper/project/homepage/member/dto/response/MultiMemberResponseDto.java
  src/main/java/keeper/project/homepage/member/dto/response/OtherMemberInfoResponseDto.java
  src/main/java/keeper/project/homepage/member/dto/response/UserMemberResponseDto.java
  src/main/java/keeper/project/homepage/member/entity/MemberEntity.java
  src/main/java/keeper/project/homepage/member/entity/MemberTypeEntity.java
  src/main/java/keeper/project/homepage/member/service/AdminMemberService.java
  src/main/java/keeper/project/homepage/member/service/MemberFindService.java
  src/main/java/keeper/project/homepage/member/service/MemberFollowService.java
  src/main/java/keeper/project/homepage/member/service/MemberService.java
  src/main/java/keeper/project/homepage/member/service/MemberUtilService.java
  src/main/java/keeper/project/homepage/sign/controller/SignInController.java
  src/main/java/keeper/project/homepage/sign/controller/SignUpController.java
  src/main/java/keeper/project/homepage/sign/dto/SignInDto.java
  src/main/java/keeper/project/homepage/sign/service/SignInService.java
  src/main/java/keeper/project/homepage/sign/service/SignUpService.java
  src/main/java/keeper/project/homepage/study/controller/StudyController.java
  src/main/java/keeper/project/homepage/study/dto/StudyDto.java
  src/main/java/keeper/project/homepage/study/entity/StudyEntity.java
  src/main/java/keeper/project/homepage/study/service/StudyService.java
  src/test/java/keeper/project/homepage/ApiControllerTestSetUp.java
  src/test/java/keeper/project/homepage/clerk/service/AdminClerkServiceTestHelper.java
  src/test/java/keeper/project/homepage/clerk/service/AdminSeminarServiceTest.java
  src/test/java/keeper/project/homepage/clerk/service/SurveyServiceTest.java
  src/test/java/keeper/project/homepage/member/controller/MemberControllerTest.java
  src/test/java/keeper/project/homepage/member/repository/MemberTypeRepositoryTest.java
Labels: ❤️ refactor
